// ─── Media Kit, Mock Data ───────────────────────────────

import type { MediaKitState } from "./types";

export const MOCK_MEDIAKIT_STATE: MediaKitState = {
  template: "minimal",
  showStats: true,
  showPricing: true,
  showPortfolio: true,
  selectedPortfolio: ["port-1", "port-2", "port-3", "port-4"],
  data: {
    profile: {
      name: "Léa",
      pseudo: "leacreative",
      bio: "Créatrice de contenu lifestyle & beauté ✨ Je partage mon quotidien, mes astuces et des moments exclusifs avec ma communauté. DM ouverts pour collaborations.",
      avatarUrl: "/mock/avatar.jpg",
      languages: ["Français", "English"],
      country: "France",
      accentColor: "var(--or, #D8A95B)",
    },
    stats: [
      { platform: "OnlyFans", followers: 28450, engagement: 8.2, avgViews: 12500, growth: 5.3 },
      { platform: "Instagram", followers: 45200, engagement: 3.8, avgViews: 8900, growth: 2.1 },
      { platform: "Twitter", followers: 12300, engagement: 2.1, avgViews: 3400, growth: 1.5 },
      { platform: "Fansly", followers: 8900, engagement: 7.5, avgViews: 5600, growth: 8.7 },
    ],
    demographics: {
      ageGroups: [
        { label: "18-24", pct: 28 },
        { label: "25-34", pct: 42 },
        { label: "35-44", pct: 18 },
        { label: "45+", pct: 12 },
      ],
      gender: [
        { label: "Hommes", pct: 68 },
        { label: "Femmes", pct: 30 },
        { label: "Autre", pct: 2 },
      ],
      countries: [
        { label: "France", pct: 45 },
        { label: "États-Unis", pct: 18 },
        { label: "Canada", pct: 12 },
        { label: "Royaume-Uni", pct: 8 },
        { label: "Autres", pct: 17 },
      ],
    },
    portfolio: [
      {
        id: "port-1",
        title: "Shooting exclusif été 2026",
        platform: "OnlyFans",
        type: "photo",
        thumbnailUrl: "",
        views: 18400,
        likes: 3200,
        engagement: 17.4,
      },
      {
        id: "port-2",
        title: "Behind the scenes : préparation shoot",
        platform: "Instagram",
        type: "reel",
        thumbnailUrl: "",
        views: 45200,
        likes: 6800,
        engagement: 15.0,
      },
      {
        id: "port-3",
        title: "Live interactif Q&A",
        platform: "OnlyFans",
        type: "video",
        thumbnailUrl: "",
        views: 9200,
        likes: 1800,
        engagement: 19.6,
      },
      {
        id: "port-4",
        title: "Story exclusive : ma routine matinale",
        platform: "Fansly",
        type: "story",
        thumbnailUrl: "",
        views: 6800,
        likes: 1100,
        engagement: 16.2,
      },
      {
        id: "port-5",
        title: "Collaboration marque X",
        platform: "Instagram",
        type: "photo",
        thumbnailUrl: "",
        views: 22100,
        likes: 4100,
        engagement: 18.6,
      },
      {
        id: "port-6",
        title: "Teaser nouveau contenu",
        platform: "Twitter",
        type: "video",
        thumbnailUrl: "",
        views: 5400,
        likes: 890,
        engagement: 16.5,
      },
    ],
    pricing: [
      { id: "price-1", label: "Post sponsorisé", price: 250, description: "Publication photo/vidéo dédiée sur le fil principal" },
      { id: "price-2", label: "Story/Reel", price: 150, description: "Story Instagram ou Reel sponsorisé (24h)" },
      { id: "price-3", label: "Mention", price: 80, description: "Mention de la marque dans 2 stories" },
      { id: "price-4", label: "Package exclusif", price: 500, description: "Post + 3 stories + contenu bonus exclusif" },
    ],
    contactEmail: "leacreative@halo.talent",
    socialLinks: [
      { platform: "Instagram", url: "https://instagram.com/leacreative" },
      { platform: "Twitter", url: "https://twitter.com/leacreative" },
      { platform: "OnlyFans", url: "https://onlyfans.com/leacreative" },
    ],
    bookingLink: "https://calendly.com/leacreative",
  },
};
