import type { CalendarEvent } from "./types";

function makeEvent(overrides: Partial<CalendarEvent> & { id: string; creator_id: string; creator_name: string; platform: string; content_preview: string; scheduled_at: string }): CalendarEvent {
  return {
    creator_avatar: null,
    content_type: "post",
    caption: "",
    hashtags: [],
    media_url: null,
    media_type: null,
    status: "planned",
    estimated_reach: null,
    estimated_engagement: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    ...overrides,
  };
}

export const calendarEvents: CalendarEvent[] = [
  // ── Clara W. (c1) ───────────────────
  makeEvent({
    id: "ev-001", creator_id: "c1", creator_name: "Clara W.",
    platform: "YouTube", content_type: "video",
    content_preview: "Ma routine beauté automne/hiver",
    scheduled_at: "2026-06-11T10:00:00Z",
    status: "planned",
    estimated_reach: 45000, estimated_engagement: 3200,
  }),
  makeEvent({
    id: "ev-002", creator_id: "c1", creator_name: "Clara W.",
    platform: "Instagram", content_type: "post",
    content_preview: "Sponsorisé : soin visage",
    scheduled_at: "2026-06-13T14:00:00Z",
    status: "planned",
    estimated_reach: 18000, estimated_engagement: 2100,
  }),
  makeEvent({
    id: "ev-003", creator_id: "c1", creator_name: "Clara W.",
    platform: "YouTube", content_type: "video",
    content_preview: "Ma morning routine",
    caption: "Ma morning routine étape par étape ✨",
    hashtags: ["#morningroutine", "#beaute", "#skincare"],
    scheduled_at: "2026-06-06T09:00:00Z",
    status: "published",
    media_url: "/mock/thumb-clara-1.jpg", media_type: "image",
    estimated_reach: 52000, estimated_engagement: 4100,
  }),
  makeEvent({
    id: "ev-004", creator_id: "c1", creator_name: "Clara W.",
    platform: "TikTok", content_type: "reel",
    content_preview: "Tuto maquillage 5min chrono",
    scheduled_at: "2026-06-15T18:00:00Z",
    status: "planned",
    estimated_reach: 35000, estimated_engagement: 5200,
  }),
  makeEvent({
    id: "ev-005", creator_id: "c1", creator_name: "Clara W.",
    platform: "Instagram", content_type: "story",
    content_preview: "Sneak peek shooting collaboration",
    scheduled_at: "2026-06-18T12:00:00Z",
    status: "draft",
    estimated_reach: 4000, estimated_engagement: 600,
  }),

  // ── Marc T. (c2) ───────────────────
  makeEvent({
    id: "ev-006", creator_id: "c2", creator_name: "Marc T.",
    platform: "Instagram", content_type: "post",
    content_preview: "Coucher de soleil en Patagonie",
    caption: "Un coucher de soleil comme on en voit qu'en Patagonie 🇦🇷",
    hashtags: ["#patagonie", "#travel", "#coucherdesoleil"],
    scheduled_at: "2026-06-10T17:30:00Z",
    status: "planned",
    estimated_reach: 28000, estimated_engagement: 3400,
  }),
  makeEvent({
    id: "ev-007", creator_id: "c2", creator_name: "Marc T.",
    platform: "TikTok", content_type: "reel",
    content_preview: "Time-lapse levé du soleil Atacama",
    scheduled_at: "2026-06-14T06:00:00Z",
    status: "planned",
    estimated_reach: 55000, estimated_engagement: 7800,
  }),
  makeEvent({
    id: "ev-008", creator_id: "c2", creator_name: "Marc T.",
    platform: "Instagram", content_type: "story",
    content_preview: "Behind the scenes tournage patron",
    scheduled_at: "2026-06-08T15:00:00Z",
    status: "published",
    estimated_reach: 12000, estimated_engagement: 1500,
  }),
  makeEvent({
    id: "ev-009", creator_id: "c2", creator_name: "Marc T.",
    platform: "YouTube", content_type: "video",
    content_preview: "Vlog : 72h à Tokyo",
    scheduled_at: "2026-06-20T11:00:00Z",
    status: "draft",
    estimated_reach: 65000, estimated_engagement: 4800,
  }),
  makeEvent({
    id: "ev-010", creator_id: "c2", creator_name: "Marc T.",
    platform: "TikTok", content_type: "live",
    content_preview: "Live Q&A voyage",
    scheduled_at: "2026-06-22T20:00:00Z",
    status: "planned",
    estimated_reach: 12000, estimated_engagement: 2500,
  }),
  makeEvent({
    id: "ev-011", creator_id: "c2", creator_name: "Marc T.",
    platform: "Instagram", content_type: "reel",
    content_preview: "Recette de pâtes minute",
    scheduled_at: "2026-07-02T12:00:00Z",
    status: "planned",
    estimated_reach: 22000, estimated_engagement: 3100,
  }),

  // ── Léa R. (c3) ───────────────────
  makeEvent({
    id: "ev-012", creator_id: "c3", creator_name: "Léa R.",
    platform: "TikTok", content_type: "reel",
    content_preview: "Reprise acoustique « Mon amour »",
    caption: "Ma reprise préférée du moment 💕",
    hashtags: ["#reprise", "#acoustique", "#chant"],
    scheduled_at: "2026-06-09T18:00:00Z",
    status: "planned",
    estimated_reach: 42000, estimated_engagement: 8600,
  }),
  makeEvent({
    id: "ev-013", creator_id: "c3", creator_name: "Léa R.",
    platform: "YouTube", content_type: "video",
    content_preview: "Cover piano + voix",
    scheduled_at: "2026-06-16T10:00:00Z",
    status: "planned",
    estimated_reach: 15000, estimated_engagement: 2200,
  }),
  makeEvent({
    id: "ev-014", creator_id: "c3", creator_name: "Léa R.",
    platform: "TikTok", content_type: "live",
    content_preview: "Live concert improvisé",
    scheduled_at: "2026-06-19T19:00:00Z",
    status: "planned",
    estimated_reach: 28000, estimated_engagement: 5200,
  }),

  // ── Inès D. (c4) ───────────────────
  makeEvent({
    id: "ev-015", creator_id: "c4", creator_name: "Inès D.",
    platform: "OnlyFans", content_type: "post",
    content_preview: "Shooting exclusif juin",
    caption: "Exclusivité du mois pour mes abonnés 💋",
    hashtags: ["#exclusif", "#shooting", "#onlyfans"],
    scheduled_at: "2026-06-12T20:00:00Z",
    status: "planned",
    media_url: "/mock/thumb-ines-1.jpg", media_type: "image",
    estimated_reach: 8000, estimated_engagement: 2400,
  }),
  makeEvent({
    id: "ev-016", creator_id: "c4", creator_name: "Inès D.",
    platform: "Instagram", content_type: "post",
    content_preview: "Collaboration marque lingerie",
    caption: "Nouvelle collaboration dont je suis trop fière ✨",
    hashtags: ["#collaboration", "#lingerie", "#marque"],
    scheduled_at: "2026-06-08T10:00:00Z",
    status: "published",
    estimated_reach: 35000, estimated_engagement: 5200,
  }),
  makeEvent({
    id: "ev-017", creator_id: "c4", creator_name: "Inès D.",
    platform: "Instagram", content_type: "story",
    content_preview: "Behind the scenes shooting",
    scheduled_at: "2026-06-07T14:00:00Z",
    status: "published",
    estimated_reach: 11000, estimated_engagement: 1400,
  }),
  makeEvent({
    id: "ev-018", creator_id: "c4", creator_name: "Inès D.",
    platform: "OnlyFans", content_type: "video",
    content_preview: "Vidéo exclusive making-of",
    scheduled_at: "2026-06-21T20:00:00Z",
    status: "planned",
    estimated_reach: 6000, estimated_engagement: 1800,
  }),
  makeEvent({
    id: "ev-019", creator_id: "c4", creator_name: "Inès D.",
    platform: "Twitter", content_type: "post",
    content_preview: "Annonce nouveau projet",
    scheduled_at: "2026-06-17T09:00:00Z",
    status: "planned",
    estimated_reach: 5000, estimated_engagement: 800,
  }),
  makeEvent({
    id: "ev-020", creator_id: "c4", creator_name: "Inès D.",
    platform: "OnlyFans", content_type: "post",
    content_preview: "Série photos plage",
    scheduled_at: "2026-07-05T19:00:00Z",
    status: "planned",
    estimated_reach: 7500, estimated_engagement: 2100,
  }),

  // ── Alex M. (c5) ───────────────────
  makeEvent({
    id: "ev-021", creator_id: "c5", creator_name: "Alex M.",
    platform: "Instagram", content_type: "post",
    content_preview: "Circuit full body à la maison",
    caption: "Pas besoin de salle pour se muscler 💪",
    hashtags: ["#fitness", "#fullbody", "#sportchezsoi"],
    scheduled_at: "2026-06-10T07:00:00Z",
    status: "planned",
    estimated_reach: 6000, estimated_engagement: 900,
  }),
  makeEvent({
    id: "ev-022", creator_id: "c5", creator_name: "Alex M.",
    platform: "TikTok", content_type: "reel",
    content_preview: "Défi 30 jours pompes",
    scheduled_at: "2026-06-13T08:00:00Z",
    status: "planned",
    estimated_reach: 15000, estimated_engagement: 3400,
  }),
  makeEvent({
    id: "ev-023", creator_id: "c5", creator_name: "Alex M.",
    platform: "Instagram", content_type: "story",
    content_preview: "Ma routine stretching",
    scheduled_at: "2026-06-05T07:30:00Z",
    status: "failed",
    estimated_reach: 2000, estimated_engagement: 300,
  }),

  // ── Emma V. (c6) ───────────────────
  makeEvent({
    id: "ev-024", creator_id: "c6", creator_name: "Emma V.",
    platform: "YouTube", content_type: "video",
    content_preview: "Tutorial production musicale",
    caption: "Tous mes secrets de production dans cette vidéo 🎹",
    hashtags: ["#production", "#musique", "#tutorial"],
    scheduled_at: "2026-06-11T16:00:00Z",
    status: "planned",
    estimated_reach: 35000, estimated_engagement: 2800,
  }),
  makeEvent({
    id: "ev-025", creator_id: "c6", creator_name: "Emma V.",
    platform: "YouTube", content_type: "video",
    content_preview: "Review matos studio",
    scheduled_at: "2026-06-18T16:00:00Z",
    status: "planned",
    estimated_reach: 28000, estimated_engagement: 2200,
  }),
  makeEvent({
    id: "ev-026", creator_id: "c6", creator_name: "Emma V.",
    platform: "YouTube", content_type: "live",
    content_preview: "Session production en direct",
    scheduled_at: "2026-06-25T18:00:00Z",
    status: "planned",
    estimated_reach: 10000, estimated_engagement: 1500,
  }),
  makeEvent({
    id: "ev-027", creator_id: "c6", creator_name: "Emma V.",
    platform: "Instagram", content_type: "post",
    content_preview: "Behind the studio",
    scheduled_at: "2026-07-01T12:00:00Z",
    status: "draft",
    estimated_reach: 8000, estimated_engagement: 1100,
  }),

  // ── Hugo P. (c7) ───────────────────
  makeEvent({
    id: "ev-028", creator_id: "c7", creator_name: "Hugo P.",
    platform: "YouTube", content_type: "video",
    content_preview: "Les clés du leadership en 2026",
    caption: "Comment j'ai construit mon leadership en 3 ans 🚀",
    hashtags: ["#leadership", "#business", "#conseil"],
    scheduled_at: "2026-06-12T11:00:00Z",
    status: "planned",
    estimated_reach: 12000, estimated_engagement: 1400,
  }),
  makeEvent({
    id: "ev-029", creator_id: "c7", creator_name: "Hugo P.",
    platform: "LinkedIn", content_type: "post",
    content_preview: "Article : Souveraineté numérique",
    scheduled_at: "2026-06-17T08:00:00Z",
    status: "planned",
    estimated_reach: 4000, estimated_engagement: 700,
  }),
  makeEvent({
    id: "ev-030", creator_id: "c7", creator_name: "Hugo P.",
    platform: "YouTube", content_type: "video",
    content_preview: "Interview entrepreneur",
    scheduled_at: "2026-06-24T11:00:00Z",
    status: "draft",
    estimated_reach: 9000, estimated_engagement: 1000,
  }),
  makeEvent({
    id: "ev-031", creator_id: "c7", creator_name: "Hugo P.",
    platform: "LinkedIn", content_type: "live",
    content_preview: "Live : Tendances business 2026",
    scheduled_at: "2026-07-08T18:00:00Z",
    status: "planned",
    estimated_reach: 3000, estimated_engagement: 500,
  }),

  // ── Plus de contenu Juillet ─────────
  makeEvent({
    id: "ev-032", creator_id: "c1", creator_name: "Clara W.",
    platform: "Instagram", content_type: "post",
    content_preview: "Nouvelle collection été",
    scheduled_at: "2026-07-03T10:00:00Z",
    status: "planned",
    estimated_reach: 20000, estimated_engagement: 2800,
  }),
  makeEvent({
    id: "ev-033", creator_id: "c3", creator_name: "Léa R.",
    platform: "YouTube", content_type: "video",
    content_preview: "Clip officiel nouveau single",
    scheduled_at: "2026-07-10T18:00:00Z",
    status: "planned",
    estimated_reach: 35000, estimated_engagement: 7200,
  }),
  makeEvent({
    id: "ev-034", creator_id: "c4", creator_name: "Inès D.",
    platform: "Instagram", content_type: "reel",
    content_preview: "OOTD été",
    scheduled_at: "2026-07-15T12:00:00Z",
    status: "planned",
    estimated_reach: 25000, estimated_engagement: 3800,
  }),
  makeEvent({
    id: "ev-035", creator_id: "c2", creator_name: "Marc T.",
    platform: "YouTube", content_type: "video",
    content_preview: "Vlog : road trip California",
    scheduled_at: "2026-07-22T11:00:00Z",
    status: "planned",
    estimated_reach: 55000, estimated_engagement: 4200,
  }),
];
