import type { Article, GlossaryEntry, ToolEntry } from "./types";
import { PRIORITY_ARTICLES } from "./priority-articles";

/* ─── Articles ─── */

export const ARTICLES: Article[] = [
  ...PRIORITY_ARTICLES,
  {
    slug: "comment-quitter-une-agence-abusif",
    title: "Comment quitter une agence abusive (OFM/MYM)",
    description: "Guide complet pour résilier votre contrat d'agence sans frais, récupérer vos comptes et protéger votre activité.",
    category: "juridique",
    date: "2026-06-08",
    readingTime: 12,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Pourquoi les créateurs veulent quitter leur agence" },
      { type: "paragraph", content: "De plus en plus de créateurs OFM et MYM cherchent à sortir de leur contrat d'agence. Les raisons sont nombreuses : commissions excessives (50-80%), manque de transparence sur les revenus, clauses d'exclusivité abusives, ou simplement l'impression de ne plus avoir le contrôle de leur activité." },
      { type: "paragraph", content: "La bonne nouvelle : la plupart des clauses abusives sont juridiquement contestables. La mauvaise : le processus peut être long et stressant si vous ne savez pas par où commencer." },
      { type: "heading", content: "1. Vérifiez votre contrat" },
      { type: "paragraph", content: "Avant toute action, relisez votre contrat. Les éléments clés à identifier sont : la durée d'engagement, le préavis, les pénalités de sortie, et les clauses de non-concurrence." },
      { type: "list", content: "Éléments à vérifier dans votre contrat :", items: [
        "Durée d'engagement : est-elle supérieure à 6 mois ? (potentiellement abusive)",
        "Préavis : 30 jours est la norme légale, au-delà c'est contestable",
        "Pénalités : des frais de sortie excessifs peuvent être requalifiés",
        "Non-concurrence : une clause qui vous empêche de travailler après la sortie",
        "Propriété des comptes : à qui appartiennent vos comptes OFM/MYM ?",
      ]},
      { type: "tip", content: "💡 Utilisez notre outil Bouclier Légal gratuit pour analyser votre contrat clause par clause et identifier les abus en 5 minutes." },
      { type: "heading", content: "2. Rassemblez les preuves" },
      { type: "paragraph", content: "Avant d'annoncer votre départ, constituez un dossier solide. Capturez vos relevés de revenus, les échanges avec votre agent, et tout document prouvant un manquement de l'agence à ses obligations." },
      { type: "list", content: "Documents à conserver :", items: [
        "Relevés de revenus OFM/MYM (tous les mois)",
        "Contrat signé et ses avenants",
        "Emails et messages avec votre agent",
        "Preuves de manque de transparence (refus de communication des revenus)",
        "Tout document médical si vous avez subi du harcèlement",
      ]},
      { type: "heading", content: "3. Envoyez une mise en demeure" },
      { type: "paragraph", content: "La mise en demeure est le premier acte juridique officiel. Elle notifie à l'agence votre intention de résilier le contrat et fixe un délai pour régulariser les éventuels manquements." },
      { type: "paragraph", content: "Nous recommandons d'envoyer votre mise en demeure en recommandé avec accusé de réception (LRAR). Conservez précieusement l'accusé de réception." },
      { type: "tip", content: "💡 Le Bouclier Légal génère automatiquement une lettre de mise en demeure personnalisée basée sur les clauses abusives détectées dans votre contrat." },
      { type: "heading", content: "4. Contactez les plateformes" },
      { type: "paragraph", content: "Si l'agence refuse de libérer vos comptes, contactez directement le support OFM ou MYM. Les plateformes prennent de plus en plus au sérieux les signalements d'agences abusives et peuvent intervenir pour vous rendre le contrôle de votre compte." },
      { type: "heading", content: "5. Protégez votre activité future" },
      { type: "paragraph", content: "Une fois libéré, signez un contrat-type transparent. Chez WTF, notre commission est marginale et dégressive (de 30% à 10%), sans frais d'entrée ni pénalité de sortie." },
    ],
    cta: {
      title: "Protégez votre activité dès maintenant",
      description: "Analysez votre contrat d'agence gratuitement avec le Bouclier Légal et recevez des recommandations personnalisées.",
      buttonLabel: "Analyser mon contrat",
      buttonHref: "/protection",
    },
  },
  {
    slug: "comprendre-les-tos-onlyfans",
    title: "Comprendre les TOS OnlyFans (guide 2026)",
    description: "Analyse complète des conditions générales OnlyFans : clauses clés, restrictions, droits des créateurs, et pièges à éviter.",
    category: "juridique",
    date: "2026-06-05",
    readingTime: 15,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Pourquoi lire les TOS OnlyFans ?" },
      { type: "paragraph", content: "Les Conditions Générales d'Utilisation (TOS) d'OnlyFans sont un document juridique qui régit votre relation avec la plateforme. Ignorer leur contenu peut entraîner la suspension de votre compte, la retenue de vos revenus, ou pire." },
      { type: "paragraph", content: "Ce guide décrypte les clauses essentielles des TOS OnlyFans mises à jour en 2026, avec des explications claires et des conseils pratiques." },
      { type: "heading", content: "Clause 1 : Propriété du contenu" },
      { type: "paragraph", content: "OnlyFans ne revendique pas la propriété de votre contenu. Vous conservez tous vos droits. Cependant, en publiant sur la plateforme, vous accordez à OnlyFans une licence mondiale, non exclusive, libre de droits, pour utiliser, reproduire et distribuer votre contenu dans le cadre du fonctionnement du service." },
      { type: "quote", content: "Cette licence est nécessaire techniquement, sans elle, OnlyFans ne pourrait pas afficher vos photos et vidéos sur la plateforme. Le piège est que cette licence survit à la résiliation de votre compte pour les contenus déjà partagés." },
      { type: "heading", content: "Clause 2 : Restrictions de contenu" },
      { type: "paragraph", content: "OnlyFans interdit strictement : les contenus impliquant des mineurs (même allusifs), la violence extrême, les actes illégaux, et les contenus non consentis. La plateforme utilise une modération automatisée et manuelle." },
      { type: "list", content: "Contenus à risque de suspension :", items: [
        "Contenu impliquant des tiers sans consentement écrit",
        "Médicaments sur ordonnance ou substances contrôlées",
        "Actes de violence simulée trop réalistes",
        "Contenu politique ou religieux explicite",
        "Liens externes redirigeant hors OnlyFans (selon la clause 6)",
      ]},
      { type: "heading", content: "Clause 3 : Paiements et commissions" },
      { type: "paragraph", content: "OnlyFans prélève 20% de commission sur tous vos revenus (abonnements, PPV, tips). Les paiements sont traités via des processeurs tiers (Stripe, etc.) et peuvent être retardés en cas de vérification d'identité." },
      { type: "heading", content: "Clause 4 : Résiliation du compte" },
      { type: "paragraph", content: "OnlyFans peut résilier votre compte à tout moment, avec ou sans préavis. En cas de résiliation pour violation des TOS, vos revenus en attente peuvent être confisqués." },
      { type: "tip", content: "💡 Pour vous protéger, conservez des sauvegardes régulières de votre contenu et de vos relevés de revenus. Ne dépendez jamais d'une seule plateforme." },
    ],
    cta: {
      title: "Besoin d'aide pour analyser un contrat ?",
      description: "Le Bouclier Légal WTF analyse vos contrats et TOS pour identifier les clauses risquées et vous propose des reformulations saines.",
      buttonLabel: "Essayer le Bouclier Légal",
      buttonHref: "/protection",
    },
  },
  {
    slug: "guide-complet-commission-management",
    title: "Guide complet des commissions de management pour créateurs OFM",
    description: "Tout comprendre sur les commissions marginales : calcul, comparaison, optimisation fiscale et stratégies pour maximiser vos revenus.",
    category: "guides",
    date: "2026-06-01",
    readingTime: 10,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Comment fonctionne la commission de management ?" },
      { type: "paragraph", content: "La commission de management est le pourcentage de vos revenus versé à votre agence ou maison de management en échange de services : support, développement de carrière, mise en relation avec des marques, etc." },
      { type: "paragraph", content: "Traditionnellement, les agences prélevaient 50% des revenus bruts, quel que soit le montant gagné. WTF a introduit un système marginal dégressif qui aligne les intérêts de la maison avec ceux du créateur." },
      { type: "heading", content: "Le système marginal expliqué" },
      { type: "paragraph", content: "Contrairement au système forfaitaire (ex: 50% sur tout), le système marginal divise vos revenus en tranches. Chaque tranche a son propre taux de commission, qui diminue à mesure que vous gagnez plus." },
      { type: "list", content: "Barème WTF (2026) :", items: [
        "0 – 5 000 € → 30%, Tranche de découverte",
        "5 000 – 20 000 € → 25%, Tranche de croissance",
        "20 000 – 50 000 € → 20%, Tranche scale",
        "50 000 – 150 000 € → 15%, Tranche elite",
        "150 000 € + → 10%, Tranche icon",
      ]},
      { type: "quote", content: "Exemple concret : sur 100 000 € de revenus annuels, la commission totale WTF est de 17 750 € (17,75% effectif). Avec une agence traditionnelle à 50%, vous auriez payé 50 000 €. Soit 32 250 € d'économies." },
      { type: "heading", content: "Comparaison avec les modèles traditionnels" },
      { type: "paragraph", content: "Le tableau ci-dessous compare ce que vous payez avec WTF vs une agence traditionnelle à 50%, en fonction de vos revenus mensuels." },
      { type: "list", content: "Simulations :", items: [
        "5 000 €/mois → WTF : 1 500 € (30%) · Agence : 2 500 € (50%) · Soit 1 000 € d'économies/mois",
        "10 000 €/mois → WTF : 2 750 € (27,5%) · Agence : 5 000 € (50%) · Soit 2 250 € d'économies/mois",
        "20 000 €/mois → WTF : 5 250 € (26,25%) · Agence : 10 000 € (50%) · Soit 4 750 € d'économies/mois",
        "50 000 €/mois → WTF : 11 250 € (22,5%) · Agence : 25 000 € (50%) · Soit 13 750 € d'économies/mois",
      ]},
      { type: "tip", content: "💡 Utilisez notre simulateur de commission interactif pour calculer précisément ce que vous paieriez avec WTF vs une agence traditionnelle." },
      { type: "heading", content: "Conseils pour négocier votre commission" },
      { type: "paragraph", content: "Que vous soyez chez WTF ou ailleurs, voici les points clés à négocier : le taux effectif (demandez un plafond), les frais annexes (exigez la transparence), la durée d'engagement (refusez au-delà de 30 jours), et la propriété de vos données et comptes." },
    ],
    cta: {
      title: "Simulez votre commission gratuitement",
      description: "Découvrez combien vous économiseriez avec WTF en 2 minutes. Simulation réaliste basée sur vos revenus actuels.",
      buttonLabel: "Simuler ma commission",
      buttonHref: "/pricing",
    },
  },
  {
    slug: "top-outils-gratuits-createurs-ofm",
    title: "Top 10 des outils gratuits pour créateurs OFM en 2026",
    description: "Les meilleurs outils gratuits pour gérer, développer et automatiser votre activité OFM : analyse de contrat, planification, IA, et plus.",
    category: "outils",
    date: "2026-05-28",
    readingTime: 8,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Les outils indispensables pour les créateurs" },
      { type: "paragraph", content: "Gérer une activité OFM demande bien plus que de la création de contenu. Entre la comptabilité, le marketing, la relation fans et la veille juridique, les bons outils font la différence." },
      { type: "paragraph", content: "Voici notre sélection des meilleurs outils gratuits, ou avec un plan free généreux, pour les créateurs OFM en 2026." },
      { type: "heading", content: "1. Bouclier Légal (WTF), Analyse de contrats" },
      { type: "paragraph", content: "Entièrement gratuit. Analyse vos contrats d'agence et TOS plateforme clause par clause, détecte les abus, génère des lettres de mise en demeure, et propose des reformulations saines." },
      { type: "heading", content: "2. Simulateur de Commission (WTF), Calcul interactif" },
      { type: "paragraph", content: "Gratuit, sans inscription. Visualisez vos commissions par tranche marginale, comparez avec le modèle 50% traditionnel, et projetez vos revenus sur 12 mois." },
      { type: "heading", content: "3. Media Kit Generator (WTF), Kit presse automatique" },
      { type: "paragraph", content: "Gratuit dans le Studio. Générez un média kit professionnel en 2 minutes avec vos stats, portfolio et tarifs. 3 templates au choix." },
      { type: "heading", content: "4. Notion, Gestion de projet" },
      { type: "paragraph", content: "Plan gratuit généreux pour organiser votre calendrier de contenu, suivre vos collaborations et centraliser vos documents." },
      { type: "heading", content: "5. Canva, Design graphique" },
      { type: "paragraph", content: "Version gratuite suffisante pour créer des visuels de qualité : stories, posts, bannières, et même des vidéos courtes." },
      { type: "heading", content: "6. Google Sheets, Comptabilité" },
      { type: "paragraph", content: "Simple et efficace pour suivre vos revenus, dépenses et commissions. Créez vos propres templates de suivi mensuel." },
      { type: "heading", content: "7. CapCut, Montage vidéo mobile" },
      { type: "paragraph", content: "Application gratuite de montage vidéo avec templates Reels/TikTok, sous-titres automatiques et effets tendance." },
      { type: "heading", content: "8. ChatGPT / Claude, Assistance IA" },
      { type: "paragraph", content: "Pour la rédaction de captions, réponses automatiques, brainstorming de contenu, et analyse de données. Les versions gratuites suffisent pour un usage créateur." },
      { type: "heading", content: "9. Calendly, Prise de rendez-vous" },
      { type: "paragraph", content: "Plan gratuit pour les créateurs qui travaillent avec des marques ou proposent des calls privés. Synchronisation calendrier automatique." },
      { type: "heading", content: "10. WTF Studio IA (gratuit), Tout-en-un" },
      { type: "paragraph", content: "Le plan gratuit de WTF Studio IA inclut 5 crédits/mois, le compositeur 3 plateformes, les templates de base, et l'inspiration feed. Pour commencer sans engagement." },
    ],
    cta: {
      title: "Centralisez vos outils avec WTF",
      description: "Le Studio IA et Atlas CRM de WTF intègrent tous les outils essentiels dans une seule plateforme. Commencez gratuitement.",
      buttonLabel: "Découvrir WTF",
      buttonHref: "/studio",
    },
  },
  {
    slug: "actualites-ofm-juin-2026",
    title: "Actualités OFM : ce qui change en juin 2026",
    description: "Les dernières actualités des plateformes OFM, MYM, Fansly : nouvelles fonctionnalités, changements de TOS, tendances du marché.",
    category: "actualites",
    date: "2026-06-10",
    readingTime: 5,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Ce mois-ci sur les plateformes" },
      { type: "paragraph", content: "Juin 2026 apporte son lot de changements sur les principales plateformes de contenu pour créateurs. Voici ce qu'il faut retenir." },
      { type: "heading", content: "OnlyFans : Nouvelle fonctionnalité Stories" },
      { type: "paragraph", content: "OnlyFans déploie progressivement une fonctionnalité Stories, similaire à Instagram. Les créateurs peuvent publier des contenus éphémères (24h) visibles par leurs abonnés. Premiers retours : engagement en hausse de 15% sur les comptes utilisateurs de la bêta." },
      { type: "heading", content: "MYM : Hausse de la commission à 25%" },
      { type: "paragraph", content: "MYM augmente sa commission de 20% à 25% à partir du 1er juillet. Une décision contestée par de nombreux créateurs. Les contrats signés avant cette date restent à l'ancien tarif jusqu'à leur renouvellement." },
      { type: "heading", content: "Fansly : Nouvel algorithme de recommandation" },
      { type: "paragraph", content: "Fansly introduit un algorithme de recommandation basé sur l'IA, similaire au FYP de TikTok. Les créateurs constatent une augmentation moyenne de 30% de la visibilité organique. Astuce : publiez des extraits courts (15-30 secondes) pour maximiser la portée." },
      { type: "heading", content: "Légal : Nouvelle régulation européenne" },
      { type: "paragraph", content: "Le Digital Services Act (DSA) européen impose de nouvelles obligations aux plateformes : transparence sur les algorithmes de recommandation, modération renforcée des contenus illicites, et droit d'information pour les créateurs en cas de restriction de compte." },
    ],
    cta: {
      title: "Restez informé avec WTF",
      description: "Le Revenue Radar et les alertes WTF vous informent en temps réel des changements qui impactent votre activité.",
      buttonLabel: "Découvrir Atlas CRM",
      buttonHref: "/features",
    },
  },
];

/* ─── Glossary ─── */

export const GLOSSARY: GlossaryEntry[] = [
  { term: "Abonnement", definition: "Revenu récurrent généré par les fans qui paient un montant fixe chaque mois pour accéder au contenu d'un créateur sur une plateforme comme OnlyFans ou MYM.", letter: "A" },
  { term: "ADN Créatif", definition: "Profil personnalisé du créateur (voix, style visuel, audience, objectifs) utilisé par l'IA WTF pour générer du contenu adapté à son identité.", letter: "A" },
  { term: "Back-catalogue", definition: "Ensemble du contenu déjà publié par un créateur. Le back-catalogue peut continuer à générer des revenus via les abonnements et les PPV.", letter: "B" },
  { term: "BYOK (Bring Your Own Key)", definition: "Fonctionnalité permettant aux créateurs d'utiliser leurs propres clés API (Anthropic, OpenAI, etc.) avec WTF Studio IA, sans commission supplémentaire.", letter: "B" },
  { term: "Bouclier Légal", definition: "Outil gratuit d'analyse de contrats d'agence pour créateurs. Identifie les clauses abusives, génère des lettres de mise en demeure et propose des reformulations saines.", letter: "B" },
  { term: "Chat Copilot", definition: "Assistant IA de WTF qui aide les créateurs à gérer leurs conversations fans avec des réponses personnalisées, des relances automatiques et une détection des intentions.", letter: "C" },
  { term: "Churn", definition: "Taux d'attrition des abonnés. Un fan en churn est un abonné qui risque de ne pas renouveler son abonnement. Le Revenue Radar de WTF détecte les signaux de churn précoce.", letter: "C" },
  { term: "Commission marginale", definition: "Système de calcul où chaque tranche de revenus est taxée à un taux différent. Contrairement au forfait, le taux effectif diminue quand les revenus augmentent.", letter: "C" },
  { term: "Contrat-type", definition: "Modèle de contrat de management transparent et équitable, utilisé par WTF, avec des conditions claires et sans clauses abusives.", letter: "C" },
  { term: "Digital Services Act (DSA)", definition: "Règlement européen imposant aux plateformes numériques des obligations de transparence sur les algorithmes, la modération et la gestion des données des créateurs.", letter: "D" },
  { term: "Engagement rate", definition: "Taux d'engagement mesurant l'interaction de l'audience avec le contenu (likes, commentaires, partages) rapporté au nombre d'abonnés ou de vues.", letter: "E" },
  { term: "FYP (For You Page)", definition: "Page de recommandation algorithmique utilisée par TikTok et désormais par Fansly. Les créateurs cherchent à apparaître sur cette page pour gagner en visibilité.", letter: "F" },
  { term: "Funnel marketing", definition: "Parcours automatisé du fan, de la découverte jusqu'à l'achat. Dans Atlas CRM, les funnels permettent de programmer des séquences de messages, emails et offres.", letter: "F" },
  { term: "Glossaire OFM", definition: "Dictionnaire des termes essentiels du monde OFM (OnlyFans Management) pour aider les créateurs à comprendre le jargon de l'industrie.", letter: "G" },
  { term: "Where Talent Forms", definition: "Plateforme tout-en-un pour créateurs OFM/MYM : management à commission marginale, Studio IA de création de contenu, et CRM marketing Atlas.", letter: "H" },
  { term: "IA générative", definition: "Intelligence artificielle capable de créer du contenu (texte, image, vidéo, audio) à partir de descriptions textuelles. Utilisée par WTF Studio IA.", letter: "I" },
  { term: "KPI (Key Performance Indicator)", definition: "Indicateur clé de performance : revenus mensuels, taux d'engagement, nombre d'abonnés, taux de churn, etc. Suivis dans le dashboard WTF.", letter: "K" },
  { term: "Média Kit", definition: "Kit de présentation professionnelle du créateur comprenant ses statistiques, son portfolio, ses tarifs et ses contacts. Généré automatiquement par le Media Kit Generator.", letter: "M" },
  { term: "Mise en demeure", definition: "Acte juridique formel notifiant à une partie son intention de résilier un contrat. Générée automatiquement par le Bouclier Légal en cas de clauses abusives.", letter: "M" },
  { term: "MYM", definition: "Plateforme de contenu pour créateurs, concurrente d'OnlyFans, particulièrement populaire en France et en Europe francophone.", letter: "M" },
  { term: "Non-concurrence", definition: "Clause contractuelle interdisant à un créateur de travailler avec d'autres plateformes ou agences après la fin de son contrat. Potentiellement abusive au-delà de 3 mois.", letter: "N" },
  { term: "OFM (OnlyFans Management)", definition: "Terme désignant l'industrie du management de créateurs sur OnlyFans et plateformes similaires. Inclut la gestion de carrière, le marketing et l'optimisation des revenus.", letter: "O" },
  { term: "OnlyFans", definition: "Plateforme de contenu par abonnement fondée en 2016. Permet aux créateurs de monétiser leur contenu via des abonnements mensuels, des PPV et des tips.", letter: "O" },
  { term: "PPV (Pay Per View)", definition: "Contenu payant supplémentaire proposé aux abonnés en plus de l'abonnement mensuel. Source de revenus importante pour les créateurs.", letter: "P" },
  { term: "Revenue Radar", definition: "Fonctionnalité exclusive d'Atlas CRM qui analyse les comportements des fans pour identifier les opportunités de revenus, les risques de churn et les ventes croisées.", letter: "R" },
  { term: "Studio IA", definition: "Suite de création de contenu assistée par IA de WTF : génération texte/image/vidéo/audio, éditeurs, templates, et publication multi-plateforme.", letter: "S" },
  { term: "Tier", definition: "Niveau ou palier dans un système de tarification. WTF propose 5 tiers de commission et 4 plans Studio avec des paliers de crédits croissants.", letter: "T" },
  { term: "Tip", definition: "Pourboire ou don volontaire envoyé par un fan à un créateur, en sus de l'abonnement. Source de revenus non négligeable pour les créateurs.", letter: "T" },
  { term: "Tone Guard", definition: "Système de vérification de conformité intégré au Chat Copilot qui analyse les messages avant envoi pour détecter les violations de TOS, tabous, ou problèmes juridiques.", letter: "T" },
  { term: "Upsell", definition: "Technique de vente consistant à proposer une offre supérieure à un client existant. Dans le contexte OFM, proposer un contenu PPV plus cher à un abonné existant.", letter: "U" },
];

/* ─── Tools ─── */

export const TOOLS: ToolEntry[] = [
  {
    slug: "bouclier-legal",
    name: "Bouclier Légal",
    description: "Analysez vos contrats d'agence clause par clause. Identifiez les abus, générez des lettres de mise en demeure, et obtenez des reformulations saines.",
    icon: "🛡️",
    href: "/protection",
    free: true,
  },
  {
    slug: "simulateur-commission",
    name: "Simulateur de Commission",
    description: "Calculez votre commission WTF en temps réel. Visualisez les tranches marginales, comparez avec le modèle 50%, et projetez vos revenus sur 12 mois.",
    icon: "📊",
    href: "/pricing",
    free: true,
  },
  {
    slug: "media-kit-generator",
    name: "Média Kit Generator",
    description: "Générez un kit de présentation professionnel en 2 minutes. Statistiques, portfolio, tarifs, choix de 3 templates design.",
    icon: "📋",
    href: "/studio/mediakit",
    free: true,
  },
  {
    slug: "commission-calculator",
    name: "Calculateur de Commission",
    description: "Version simplifiée du simulateur. Idéal pour un calcul rapide sans navigation. Entrez vos revenus, obtenez votre commission instantanément.",
    icon: "🧮",
    href: "/commissions",
    free: true,
  },
  {
    slug: "contrat-type",
    name: "Contrat-Type WTF",
    description: "Consultez le modèle de contrat de management WTF. Transparent, sans clauses abusives, avec commission marginale et sortie 30 jours.",
    icon: "📄",
    href: "/contrat-type",
    free: true,
  },
  {
    slug: "studio-ia",
    name: "Studio IA (Plan Gratuit)",
    description: "Créez, éditez et publiez du contenu avec l'IA. 5 crédits offerts par mois, 3 plateformes, templates et inspiration feed.",
    icon: "✨",
    href: "/studio",
    free: true,
  },
  {
    slug: "chat-copilot",
    name: "Chat Copilot",
    description: "Assistant IA pour gérer vos conversations fans. Réponses personnalisées, Tone Guard, relances automatiques et détection d'intention.",
    icon: "💬",
    href: "/dashboard/atlas/revenue-inbox",
    free: false,
  },
  {
    slug: "revenue-radar",
    name: "Revenue Radar",
    description: "Détection automatique des opportunités de revenus, des fans à risque de churn, et des recommandations d'upsell personnalisées.",
    icon: "📡",
    href: "/dashboard/atlas/revenue-radar",
    free: false,
  },
];
