import type { Article } from "./types";

export const PRIORITY_ARTICLES: Article[] = [
  {
    slug: "comment-choisir-agence-management-createur",
    title: "Comment choisir une agence de management créateur",
    description: "Les critères objectifs pour évaluer une agence, les questions à poser avant de signer, et les alternatives au management traditionnel.",
    category: "commissions",
    date: "2026-06-10",
    readingTime: 12,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Les 3 modèles de management : agence traditionnelle, maison de management, indépendant" },
      { type: "paragraph", content: "Avant de chercher une agence, comprenez qu'il existe trois grands modèles. L'agence traditionnelle prélève un pourcentage fixe (souvent 40 à 60%) sur tous vos revenus, en échange de services plus ou moins définis. La maison de management comme WTF propose une commission marginale dégressive avec un contrat-type transparent et des services clairement listés. Le modèle indépendant consiste à tout gérer soi-même ou à déléguer à des prestataires ponctuels (comptable, community manager, avocat). Chaque modèle a ses avantages et ses risques." },
      { type: "heading", content: "Les 8 critères pour évaluer une agence" },
      { type: "paragraph", content: "Voici les huit critères objectifs sur lesquels vous devez évaluer toute agence avant de signer." },
      { type: "list", content: "Critères d'évaluation :", items: [
        "Transparence des commissions : le taux est-il clairement affiché ? Y a-t-il des frais cachés ?",
        "Contrat-type : l'agence peut-elle vous montrer un exemplaire de contrat avant tout engagement ?",
        "Références vérifiables : peut-elle vous mettre en contact avec des créateurs qu'elle manage déjà ?",
        "Outils et technologies : quels outils met-elle à disposition (CRM, analytics, création de contenu) ?",
        "Équipe dédiée : aurez-vous un interlocuteur identifié ou serez-vous noyé dans un portefeuille ?",
        "Conditions de sortie : quel est le préavis ? Y a-t-il des pénalités ? Récupérez-vous vos comptes ?",
        "Reporting : à quelle fréquence recevez-vous un rapport sur vos performances et vos revenus ?",
        "Spécialisation secteur : l'agence connaît-elle votre secteur (Glamour, Musique, Sport, etc.) ?",
      ]},
      { type: "heading", content: "Questions à poser lors du premier appel avec une agence" },
      { type: "paragraph", content: "Le premier appel est un entretien d'embauche, c'est vous qui recrutez. Préparez vos questions à l'avance et prenez des notes." },
      { type: "list", content: "Questions essentielles à poser :", items: [
        "Combien de créateurs managez-vous actuellement ? Quelle est la taille moyenne des comptes ?",
        "Puis-je voir un exemple de rapport mensuel que vous fournissez à vos créateurs ?",
        "Qui sera mon interlocuteur au quotidien ? Puis-je le rencontrer avant de signer ?",
        "Que se passe-t-il si je veux partir dans 3 mois ? Dans 6 mois ?",
        "Quels sont les 3 plus gros problèmes que vos créateurs rencontrent avec vous ?",
      ]},
      { type: "heading", content: "Les signaux d'alerte qui doivent vous faire fuir" },
      { type: "paragraph", content: "Certains comportements doivent vous alerter immédiatement. Si une agence présente un seul de ces signaux, réfléchissez à deux fois avant de signer." },
      { type: "list", content: "Signaux d'alerte :", items: [
        "L'agence refuse de vous montrer un contrat avant la signature.",
        "Elle vous promet des revenus spécifiques ou une croissance garantie.",
        "Elle vous demande de changer vos mots de passe avant la signature du contrat.",
        "Elle ne peut citer aucun créateur actuel comme référence.",
        "Elle vous met la pression pour signer rapidement (« offre valable 48h »).",
        "Ses seuls arguments sont des chiffres de revenus sans expliquer comment elle les obtient.",
      ]},
      { type: "heading", content: "Checklist de comparaison entre 2 ou 3 agences" },
      { type: "paragraph", content: "Si vous hésitez entre plusieurs agences, créez un tableau comparatif simple. Colonnes : commission effective, services inclus, durée d'engagement, conditions de sortie, références vérifiées, outils fournis, spécialisation secteur. Attribuez une note de 1 à 5 pour chaque critère et faites le total." },
      { type: "tip", content: "Ne choisissez pas l'agence la moins chère. Choisissez la plus transparente. Une commission à 20% avec des frais cachés peut vous coûter plus qu'une commission à 30% tout inclus." },
      { type: "heading", content: "Pourquoi la commission marginale change la donne" },
      { type: "paragraph", content: "La plupart des agences prélèvent un pourcentage fixe sur tous vos revenus, quel que soit le montant. Une commission marginale fonctionne par tranches : les premiers euros sont plus taxés que les suivants. Concrètement, plus vous gagnez, plus votre taux effectif baisse. C'est le modèle WTF." },
      { type: "paragraph", content: "Avec une agence à 50% fixe, sur 100 000€ de revenus annuels, vous payez 50 000€ de commission. Avec le modèle marginal WTF, vous payez environ 17 750€. Cette différence de 32 250€ n'est pas une promesse, c'est un calcul." },
    ],
    cta: {
      title: "Comparez votre commission actuelle",
      description: "Utilisez le simulateur WTF pour calculer ce que vous paieriez avec une commission marginale transparente.",
      buttonLabel: "Simuler ma commission",
      buttonHref: "/pricing",
    },
  },
  {
    slug: "pourquoi-transparence-commissions-compte",
    title: "Pourquoi la transparence des commissions compte",
    description: "Comment les commissions opaques pénalisent les créateurs, l'impact réel d'une commission à 50%, et ce que la transparence change concrètement.",
    category: "commissions",
    date: "2026-06-09",
    readingTime: 10,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Commission forfaitaire vs marginale : explication visuelle" },
      { type: "paragraph", content: "Imaginez deux seaux. Dans le premier (forfaitaire), l'agence prend 50% de chaque euro que vous gagnez, du premier au dernier. Dans le second (marginal), l'agence prend un pourcentage qui diminue à mesure que le seau se remplit. Le système forfaitaire est plus simple à expliquer, c'est pour cela qu'il est dominant. Mais il est mécaniquement désavantageux pour le créateur." },
      { type: "paragraph", content: "Prenons un exemple concret. Vous gagnez 10 000€ un mois. Commission forfaitaire à 50% : l'agence prend 5 000€. Commission marginale WTF (30% sur les premiers 5 000€, 25% sur le reste) : l'agence prend 2 750€. Vous gardez 2 250€ de plus. Sur un an, cette différence peut représenter des dizaines de milliers d'euros." },
      { type: "heading", content: "Le coût caché d'une commission à 50% sur 12 mois" },
      { type: "paragraph", content: "Faisons le calcul sur une année complète avec un créateur qui gagne 8 000€ par mois en moyenne. Avec une commission forfaitaire à 50%, il paie 48 000€ par an. Avec le barème marginal WTF, il paie environ 27 600€. Différence : 20 400€. C'est l'équivalent d'une belle voiture, d'un apport pour un appartement, ou de trois mois de vacances." },
      { type: "heading", content: "Frais annexes : ce que les agences ne disent pas" },
      { type: "paragraph", content: "Au-delà du pourcentage affiché, certaines agences ajoutent des frais qui peuvent considérablement alourdir la note : frais de dossier à l'entrée, frais de gestion mensuels fixes, commissions sur les partenariats (en plus de la commission sur les revenus plateforme), frais de résiliation. Demandez toujours une liste exhaustive des frais avant de signer." },
      { type: "heading", content: "Comment vérifier la transparence de votre agence actuelle" },
      { type: "list", content: "Checklist de transparence :", items: [
        "Recevez-vous un relevé détaillé chaque mois avec le calcul précis de la commission ?",
        "Pouvez-vous accéder directement à vos statistiques de revenus sans passer par l'agence ?",
        "L'agence vous facture-t-elle des frais qui n'étaient pas mentionnés dans le contrat initial ?",
        "Quand vous posez une question sur votre rémunération, obtenez-vous une réponse claire en moins de 48h ?",
        "Savez-vous exactement combien vous gagnez par plateforme, par type de contenu, et par fan ?",
      ]},
      { type: "heading", content: "L'impact psychologique de savoir exactement combien vous gagnez" },
      { type: "paragraph", content: "La transparence n'est pas qu'une question d'argent. C'est une question de contrôle. Un créateur qui ne sait pas exactement combien il gagne, combien on lui prélève, et pourquoi, vit dans une forme d'incertitude permanente. Cette incertitude est épuisante. Elle empêche de se projeter, d'investir, de faire des choix éclairés." },
      { type: "quote", content: "La transparence n'est pas un argument marketing. C'est la condition minimale d'une relation de confiance entre un créateur et sa maison de management." },
      { type: "heading", content: "Le modèle WTF : commission marginale dégressive expliquée" },
      { type: "paragraph", content: "Le barème WTF est public : 30% jusqu'à 5 000€, puis 25% jusqu'à 20 000€, puis 20% jusqu'à 50 000€, puis 15% jusqu'à 150 000€, puis 10% au-delà. Ce barème est le même pour tous les créateurs. Il n'y a pas de négociation secrète, pas de traitement de faveur. Vous savez exactement ce que vous paierez avant de signer." },
    ],
    cta: {
      title: "Simulez votre commission réelle",
      description: "Notre simulateur gratuit vous montre en 2 minutes combien vous économiseriez avec une commission transparente.",
      buttonLabel: "Calculer ma commission",
      buttonHref: "/pricing",
    },
  },
  {
    slug: "crm-createur-centraliser-donnees",
    title: "CRM créateur : pourquoi centraliser ses données",
    description: "Centraliser ses données fans dans un CRM permet de mieux comprendre son audience, personnaliser ses offres et augmenter ses revenus sans travailler plus.",
    category: "ia-crm",
    date: "2026-06-08",
    readingTime: 11,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Qu'est-ce qu'un CRM créateur et en quoi il diffère d'un CRM classique" },
      { type: "paragraph", content: "Un CRM (Customer Relationship Management) est un outil qui centralise toutes les informations sur vos clients. Dans le monde du conseil ou du e-commerce, on utilise Salesforce ou HubSpot. Mais ces outils ne sont pas conçus pour les créateurs de contenu : ils ne gèrent pas les abonnements, les PPV, les conversations multi-plateformes ou les spécificités d'OnlyFans et MYM." },
      { type: "paragraph", content: "Un CRM créateur comme Atlas CRM est pensé dès le départ pour l'activité d'un créateur : il connecte vos plateformes, agrège vos données fans, segmente votre audience, automatise vos relances, et vous donne une vue claire de votre activité." },
      { type: "heading", content: "Les 5 données fans essentielles à suivre" },
      { type: "list", content: "Données indispensables par fan :", items: [
        "Historique d'achats : quels PPV a-t-il achetés, à quel prix, quand ?",
        "Niveau d'engagement : à quelle fréquence like-t-il, commente-t-il, répond-t-il à vos messages ?",
        "Ancienneté : depuis combien de temps est-il abonné ? A-t-il déjà résilié puis repris un abonnement ?",
        "Budgets : quel est son panier moyen ? Quel est le prix maximum qu'il a déjà payé pour un PPV ?",
        "Préférences de contenu : quels types de contenu consomme-t-il le plus (photos, vidéos, messages privés) ?",
      ]},
      { type: "heading", content: "Segmentation : comment diviser votre base pour mieux vendre" },
      { type: "paragraph", content: "Tous vos fans ne sont pas identiques, et leur envoyer le même message à tous est une erreur. La segmentation consiste à diviser votre base en groupes homogènes pour adapter votre communication et vos offres. Les segments les plus courants : nouveaux abonnés (à accueillir et éduquer), fans réguliers (à fidéliser), gros acheteurs (à choyer), fans dormants (à réactiver)." },
      { type: "heading", content: "Automatisation : les séquences qui font gagner du temps" },
      { type: "paragraph", content: "Une séquence automatisée est une série de messages programmés qui s'envoient automatiquement selon des déclencheurs. Exemples : séquence de bienvenue pour les nouveaux abonnés (message 1 à J+1, message 2 à J+3, offre spéciale à J+7), séquence de réactivation pour les fans inactifs depuis 30 jours, séquence d'upsell après un premier achat." },
      { type: "tip", content: "Une séquence de bienvenue bien conçue peut augmenter le revenu par nouvel abonné de 20 à 40% dès le premier mois. C'est l'automatisation la plus rentable à mettre en place." },
      { type: "heading", content: "Détection du churn : repérer un fan qui va partir avant qu'il ne parte" },
      { type: "paragraph", content: "Le churn (attrition) est le pourcentage d'abonnés qui se désabonnent chaque mois. Un bon CRM créateur détecte les signaux faibles : baisse de l'engagement, diminution des achats, espacement des connexions. En intervenant avant le désabonnement (message personnalisé, offre de rétention), vous pouvez réduire votre taux de churn." },
      { type: "heading", content: "Cas concret : comment Atlas CRM structure l'activité d'un créateur" },
      { type: "paragraph", content: "Atlas CRM intègre le Revenue Radar (détection d'opportunités), le Chat Copilot (réponses assistées), le PPV Copilot (recommandations de prix), et le Fan Brain (analyse comportementale). Le tout est accessible depuis un dashboard unique qui vous montre l'essentiel en un coup d'œil : revenus du jour, nouveaux abonnés, messages en attente, opportunités détectées." },
    ],
    cta: {
      title: "Découvrez Atlas CRM",
      description: "Centralisez vos données fans, segmentez votre audience et automatisez vos relances.",
      buttonLabel: "Explorer Atlas CRM",
      buttonHref: "/features",
    },
  },
  {
    slug: "ia-createurs-preparer-sans-perdre-controle",
    title: "IA et créateurs : préparer sans perdre le contrôle",
    description: "L'IA générative transforme la création de contenu. Comment l'utiliser comme un outil sans perdre votre authenticité ni votre contrôle créatif.",
    category: "ia-crm",
    date: "2026-06-07",
    readingTime: 14,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Ce que l'IA peut faire pour un créateur aujourd'hui" },
      { type: "paragraph", content: "L'IA générative a fait des progrès spectaculaires. Aujourd'hui, elle peut vous aider à : générer des variantes de vos visuels dans votre style, rédiger des légendes et des messages fans, suggérer des idées de contenu basées sur vos performances passées, traduire vos contenus pour une audience internationale, automatiser vos réponses aux questions fréquentes." },
      { type: "paragraph", content: "Ce qu'elle ne peut pas faire : remplacer votre personnalité, votre vécu, votre relation authentique avec vos fans. L'IA est un outil, pas un créateur. La valeur de votre contenu vient de vous, pas de la machine qui vous assiste." },
      { type: "heading", content: "L'ADN Créatif : comment WTF personnalise l'IA à votre identité" },
      { type: "paragraph", content: "Le problème des IA génériques (ChatGPT, Midjourney) est qu'elles produisent un contenu standardisé. L'ADN Créatif WTF résout ce problème : vous décrivez votre style (visuel, tonalité, thèmes, tabous), et l'IA apprend à créer du contenu qui vous ressemble. Plus vous l'utilisez, plus elle s'affine." },
      { type: "heading", content: "Deepfakes et usurpation : les risques réels et comment s'en protéger" },
      { type: "paragraph", content: "Le revers de la médaille : les mêmes technologies qui vous aident peuvent être utilisées contre vous. Les deepfakes (vidéos truquées utilisant votre visage ou votre voix) sont une menace croissante pour les créateurs. La protection passe par la vigilance (surveiller les signalements), la réactivité (faire supprimer rapidement les contenus usurpateurs), et la prévention (filigraner vos contenus, limiter la résolution publique)." },
      { type: "heading", content: "Transparence avec votre audience : faut-il dire que vous utilisez l'IA ?" },
      { type: "paragraph", content: "C'est la question éthique centrale. Notre position chez WTF : la transparence est toujours préférable. Vous n'avez pas à mentionner chaque assistance IA, mais si l'IA a joué un rôle significatif dans une création (image générée, texte co-écrit), le mentionner renforce la confiance de votre audience. Les fans valorisent l'authenticité, pas la prouesse technique." },
      { type: "heading", content: "Le futur : ce que l'IA va changer dans les 2 prochaines années" },
      { type: "paragraph", content: "Les tendances à suivre : la vidéo générative va devenir aussi accessible que l'image générative aujourd'hui, les voix de synthèse seront indiscernables des voix humaines, les plateformes intégreront des outils IA natifs, et la frontière entre contenu humain et contenu assisté deviendra de plus en plus floue. Les créateurs qui auront appris à maîtriser ces outils sans y perdre leur identité seront les mieux positionnés." },
    ],
    cta: {
      title: "Essayez le Studio IA WTF",
      description: "Créez du contenu avec une IA qui respecte votre identité. 5 crédits offerts par mois.",
      buttonLabel: "Découvrir le Studio IA",
      buttonHref: "/studio",
    },
  },
  {
    slug: "droit-image-questions-avant-collaboration",
    title: "Droit d'image : les questions à poser avant une collaboration",
    description: "Checklist juridique essentielle pour protéger votre image lors de toute collaboration avec une marque, un photographe ou un autre créateur.",
    category: "juridique",
    date: "2026-06-06",
    readingTime: 10,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Droit d'image : définition simple et cadre légal en France" },
      { type: "paragraph", content: "Le droit à l'image est le droit de toute personne à s'opposer à la publication de son image sans son autorisation. Il est fondé sur l'article 9 du Code civil qui protège le droit au respect de la vie privée. En tant que créateur, votre image est votre outil de travail, elle a une valeur économique qu'il faut protéger." },
      { type: "tip", content: "Le droit à l'image s'applique aussi aux photos prises dans un lieu public. Ce n'est pas parce qu'une photo a été prise dans la rue que n'importe qui peut l'utiliser commercialement." },
      { type: "heading", content: "Les 7 questions à poser avant d'autoriser l'utilisation de votre image" },
      { type: "list", content: "Questions essentielles :", items: [
        "Qui va utiliser mon image ? (marque, média, agence, autre créateur)",
        "Sur quels supports ? (réseaux sociaux, affichage, site web, publicité payante, télévision)",
        "Pendant combien de temps ? (une semaine, un mois, un an, indéfiniment)",
        "Dans quels pays ? (France seulement, Europe, monde entier)",
        "Quel est le contexte ? (article, publicité, post organique, campagne sponsorisée)",
        "Mon image sera-t-elle modifiée ? (recadrage, filtre, retouche, montage)",
        "Puis-je révoquer mon autorisation ? Sous quel préavis ?",
      ]},
      { type: "heading", content: "Durée, territoire, supports : les 3 dimensions à toujours négocier" },
      { type: "paragraph", content: "Toute autorisation d'utilisation de votre image doit préciser ces trois dimensions. Sans cela, l'autorisation est trop large et vous perdez le contrôle. La durée doit être limitée (une campagne a une fin). Le territoire doit être défini (une marque locale n'a pas besoin d'une licence mondiale). Les supports doivent être listés (un post Instagram n'est pas une affiche 4x3)." },
      { type: "heading", content: "Le cas particulier des réseaux sociaux et du contenu éphémère" },
      { type: "paragraph", content: "Les stories Instagram, les TikTok, les Reels posent des questions spécifiques. Une story disparaît en 24h, mais peut être capturée et republiée. Précisez toujours que le contenu ne peut pas être réutilisé sans votre accord, même après disparition de la story." },
      { type: "heading", content: "Que faire si votre image est utilisée sans autorisation ?" },
      { type: "list", content: "Les 4 étapes en cas d'utilisation non autorisée :", items: [
        "Contactez la personne ou l'entreprise et demandez le retrait immédiat par écrit (gardez une trace)",
        "Si pas de réponse sous 48h, envoyez une mise en demeure formelle",
        "Signalez le contenu à la plateforme (Instagram, TikTok, etc.) pour violation de droits",
        "Si la situation persiste, consultez un avocat spécialisé en droit de l'image",
      ]},
      { type: "tip", content: "Le Bouclier Légal WTF peut vous aider à analyser une clause de droit d'image dans un contrat et à identifier les formulations problématiques." },
    ],
    cta: {
      title: "Protégez votre image avec WTF Lex",
      description: "Analysez vos contrats de collaboration et identifiez les clauses abusives liées à votre droit d'image.",
      buttonLabel: "Essayer WTF Lex",
      buttonHref: "/lex",
    },
  },
  {
    slug: "securite-comptes-createurs-checklist",
    title: "Sécurité des comptes créateurs : checklist essentielle",
    description: "Une checklist complète en 12 points pour sécuriser vos comptes de créateur et éviter les intrusions, les usurpations et les pertes de revenus.",
    category: "protection",
    date: "2026-06-05",
    readingTime: 9,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Pourquoi les comptes de créateurs sont des cibles privilégiées" },
      { type: "paragraph", content: "Un compte de créateur n'est pas un compte personnel comme les autres. C'est un outil de travail qui génère des revenus, contient du contenu sensible, et donne accès à une audience. Le pirater, c'est prendre le contrôle de votre entreprise. Les motivations des pirates : extorsion (rendre le compte contre rançon), usurpation (se faire passer pour vous), revente (vendre le compte à un tiers)." },
      { type: "heading", content: "Les 3 vecteurs d'attaque les plus fréquents" },
      { type: "list", content: "Comment les comptes sont piratés :", items: [
        "Phishing : vous recevez un email ou un message qui semble provenir d'OnlyFans vous demandant de vous reconnecter. Le lien mène vers une copie du site qui vole votre mot de passe.",
        "Force brute : un pirate utilise un logiciel qui teste des milliers de mots de passe courants jusqu'à trouver le bon. Les mots de passe courts ou simples cèdent en quelques minutes.",
        "Ingénierie sociale : le pirate contacte le support client de la plateforme en se faisant passer pour vous, avec des informations personnelles trouvées en ligne, et obtient un changement de mot de passe.",
      ]},
      { type: "heading", content: "Checklist 12 points pour sécuriser vos comptes" },
      { type: "list", content: "La checklist de sécurité complète :", items: [
        "Activez l'authentification à deux facteurs (2FA) sur tous vos comptes, pas seulement les plateformes de contenu",
        "Utilisez une application d'authentification (Authy, Google Authenticator) plutôt que les SMS, plus faciles à intercepter",
        "Créez des mots de passe uniques d'au moins 16 caractères pour chaque compte (utilisez un gestionnaire de mots de passe)",
        "Vérifiez régulièrement les appareils connectés à vos comptes et déconnectez ceux que vous ne reconnaissez pas",
        "Activez les alertes de connexion (email ou notification à chaque nouvelle connexion)",
        "Utilisez une adresse email dédiée à votre activité de créateur, distincte de votre email personnel",
        "Ne partagez jamais vos identifiants avec votre agence, utilisez des accès délégués quand c'est possible",
        "Vérifiez que votre numéro de téléphone de récupération est à jour sur toutes les plateformes",
        "Faites des sauvegardes régulières de tout votre contenu sur un stockage sécurisé (Content Vault)",
        "Ne cliquez jamais sur un lien de connexion reçu par email ou message, allez toujours directement sur le site",
        "Méfiez-vous des demandes de vérification d'identité non sollicitées, les plateformes ne vous demandent jamais votre mot de passe",
        "Utilisez une clé de sécurité physique (YubiKey) pour vos comptes les plus critiques si vos revenus dépassent 10 000€/mois",
      ]},
      { type: "heading", content: "Que faire en cas de piratage : les 5 premières actions" },
      { type: "list", content: "Plan d'urgence :", items: [
        "Contactez immédiatement le support de la plateforme, toutes les plateformes ont une procédure d'urgence pour les comptes vérifiés",
        "Changez le mot de passe de votre adresse email associée au compte, c'est la clé de voûte de votre sécurité",
        "Vérifiez et révoquez toutes les sessions actives sur vos autres comptes (email, réseaux sociaux, banque)",
        "Prévenez votre agence ou votre manager pour qu'ils puissent bloquer les transactions en cours",
        "Documentez tout : captures d'écran, emails, horaires, ces preuves seront utiles pour l'enquête et l'assurance",
      ]},
      { type: "tip", content: "Avec WTF, tous les comptes sont protégés par 2FA obligatoire, audit log complet, et alertes de connexion en temps réel. La sécurité n'est pas une option, c'est la base." },
    ],
    cta: {
      title: "Passez à l'action maintenant",
      description: "Activez la 2FA sur vos comptes et découvrez comment WTF sécurise votre activité de créateur.",
      buttonLabel: "Découvrir la sécurité WTF",
      buttonHref: "/security",
    },
  },
  {
    slug: "construire-image-premium-duree",
    title: "Construire une image premium sur la durée",
    description: "Les principes d'une image de marque forte et cohérente pour les créateurs : identité visuelle, ton éditorial, storytelling et cohérence cross-platform.",
    category: "image-strategie",
    date: "2026-06-04",
    readingTime: 13,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Image de marque pour créateur : pourquoi c'est votre actif le plus précieux" },
      { type: "paragraph", content: "Votre image de marque est ce qui reste quand on retire le contenu. C'est la raison pour laquelle un fan vous choisit plutôt qu'un autre créateur qui propose un contenu similaire. Une image de marque forte vous permet de : justifier des prix plus élevés, attirer des collaborations plus prestigieuses, fidéliser votre audience au-delà d'un contenu spécifique, et survivre aux changements de plateforme ou de tendance." },
      { type: "heading", content: "Les 4 piliers d'une identité visuelle cohérente" },
      { type: "list", content: "Les fondamentaux visuels :", items: [
        "Palette de couleurs : choisissez 3 à 5 couleurs et tenez-vous-y. Elles créent une reconnaissance immédiate.",
        "Typographie : une police pour les titres, une pour le corps de texte. La cohérence typographique est un marqueur de qualité.",
        "Style photo/vidéo : lumière, cadrage, retouche. Votre style visuel doit être identifiable en un coup d'œil.",
        "Éléments graphiques : logo, motif, filigrane. Des éléments récurrents qui signent votre contenu.",
      ]},
      { type: "heading", content: "Trouver votre ton éditorial et vous y tenir" },
      { type: "paragraph", content: "Le ton éditorial, c'est la personnalité de votre communication. Êtes-vous chaleureux et proche, ou distant et mystérieux ? Drôle ou sérieux ? Direct ou suggestif ? L'important n'est pas quel ton vous choisissez, mais de le garder cohérent. Un créateur qui oscille entre proximité affectueuse et distance professionnelle déroute son audience." },
      { type: "heading", content: "Storytelling créateur : comment raconter votre parcours sans tout dévoiler" },
      { type: "paragraph", content: "Le storytelling est l'art de raconter une histoire qui crée une connexion émotionnelle avec votre audience. Mais pour un créateur, la frontière entre storytelling et vie privée est mince. La règle : partagez votre parcours professionnel, vos valeurs, votre vision, mais gardez pour vous ce qui relève de l'intime. Vous n'êtes pas obligé de tout montrer pour être authentique." },
      { type: "heading", content: "Cohérence cross-platform : adapter sans se trahir" },
      { type: "paragraph", content: "Vous êtes présent sur plusieurs plateformes, mais votre identité doit rester reconnaissable partout. Adaptez le format (une story Instagram n'est pas une vidéo YouTube), mais gardez votre palette de couleurs, votre ton, votre logo. Un fan qui vous découvre sur TikTok doit pouvoir vous reconnaître instantanément sur Instagram." },
      { type: "heading", content: "Rebranding : quand et comment faire évoluer votre image" },
      { type: "paragraph", content: "Votre image de marque n'est pas figée. Elle évolue avec vous. Un rebranding peut être nécessaire quand : votre contenu a changé de nature, votre audience a évolué, vous voulez vous positionner sur un segment plus premium. Faites-le progressivement, un changement brutal perturbe votre audience. Testez les nouvelles directions sur une partie de votre contenu avant de généraliser." },
    ],
    cta: {
      title: "Construisez votre image avec WTF",
      description: "Le Studio IA et le Media Kit Generator vous aident à créer et maintenir une identité visuelle premium.",
      buttonLabel: "Essayer le Studio IA",
      buttonHref: "/studio",
    },
  },
  {
    slug: "erreurs-frequentes-collaborations-createur-agence",
    title: "Les erreurs fréquentes dans les collaborations créateur-agence",
    description: "Absence de contrat écrit, exclusivité disproportionnée, commissions opaques : les pièges les plus courants et comment les éviter.",
    category: "juridique",
    date: "2026-06-03",
    readingTime: 11,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Erreur n°1 : Travailler sans contrat écrit" },
      { type: "paragraph", content: "C'est l'erreur la plus fréquente et la plus coûteuse. Un accord oral n'a aucune valeur juridique en cas de litige. Même si vous faites confiance à la personne en face, un contrat écrit protège les deux parties. Il clarifie les attentes, les obligations et les conditions de sortie." },
      { type: "heading", content: "Erreur n°2 : Accepter une exclusivité sans contrepartie" },
      { type: "paragraph", content: "L'exclusivité est une contrainte forte : elle vous empêche de travailler avec d'autres partenaires. Elle doit toujours avoir une contrepartie proportionnée, une commission plus basse, un minimum garanti, des services supplémentaires. Une exclusivité sans contrepartie est un signal d'alerte majeur." },
      { type: "heading", content: "Erreur n°3 : Ne pas vérifier la propriété de ses comptes" },
      { type: "paragraph", content: "Certaines agences créent les comptes de leurs créateurs avec leurs propres identifiants. Résultat : si vous quittez l'agence, vous perdez l'accès à vos comptes et à votre audience. Vérifiez toujours que vos comptes sont créés avec votre email, votre numéro de téléphone, et vos informations d'identité." },
      { type: "heading", content: "Erreur n°4 : Ignorer les clauses de non-concurrence post-contractuelles" },
      { type: "paragraph", content: "Une clause de non-concurrence peut vous empêcher d'exercer votre activité pendant des mois après la fin du contrat. Ces clauses sont encadrées par la loi : elles doivent être limitées dans le temps, dans l'espace, et dans le type d'activité. Une clause qui vous interdit toute activité de créateur pendant 2 ans sur tout le territoire est presque certainement abusive." },
      { type: "heading", content: "Erreur n°5 : Ne pas documenter les échanges avec son agence" },
      { type: "paragraph", content: "En cas de conflit, ce sont les traces écrites qui feront la différence. Conservez tous les emails, les messages, les relevés de revenus. Si un échange important a lieu par téléphone, envoyez un email récapitulatif juste après (« Comme convenu lors de notre appel... »). Cette habitude vous protège." },
      { type: "heading", content: "Erreur n°6 : Rester par peur ou par méconnaissance de ses droits" },
      { type: "paragraph", content: "Beaucoup de créateurs restent dans des situations défavorables parce qu'ils ignorent leurs droits ou qu'ils craignent des représailles. Sachez que : la plupart des clauses abusives sont contestables juridiquement, vous avez le droit de demander des comptes sur votre rémunération, et vous pouvez changer d'agence si celle-ci ne remplit pas ses obligations." },
      { type: "quote", content: "Rester par peur est la seule erreur dont vous ne pourrez pas tirer de leçon. Toutes les autres se corrigent." },
    ],
    cta: {
      title: "Analysez votre contrat gratuitement",
      description: "Le Bouclier Légal WTF analyse votre contrat d'agence, détecte les clauses abusives et vous donne des recommandations personnalisées.",
      buttonLabel: "Analyser mon contrat",
      buttonHref: "/protection",
    },
  },
  {
    slug: "preparer-dossier-avant-consulter-avocat",
    title: "Comment préparer un dossier avant de consulter un avocat",
    description: "Un guide pratique pour préparer efficacement votre dossier juridique : documents à rassembler, chronologie, questions à poser, budget à anticiper.",
    category: "juridique",
    date: "2026-06-02",
    readingTime: 10,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Pourquoi un dossier bien préparé réduit vos frais d'avocat" },
      { type: "paragraph", content: "Un avocat facture son temps, pas le résultat. Plus votre dossier est clair et structuré, moins il passera de temps à le comprendre, et moins la consultation vous coûtera. Un dossier bien préparé peut réduire le temps de consultation de 30 à 50%, et augmente significativement la qualité des conseils reçus." },
      { type: "heading", content: "Les 8 documents à rassembler avant le premier rendez-vous" },
      { type: "list", content: "Checklist documentaire :", items: [
        "Le contrat ou les contrats concernés, avec tous les avenants et annexes",
        "Tous les échanges écrits avec la partie adverse (emails, messages, courriers), classés chronologiquement",
        "Les relevés de revenus et de commissions, mois par mois, depuis le début de la collaboration",
        "Les captures d'écran de tout élément pertinent (conversations, publications, statistiques)",
        "Une copie de vos pièces d'identité et justificatifs de domicile",
        "Toute correspondance antérieure avec un autre avocat ou conseil sur le même sujet",
        "Les conditions générales des plateformes concernées (OnlyFans, MYM, etc.)",
        "Un tableau récapitulatif des préjudices estimés (financiers, moraux, professionnels)",
      ]},
      { type: "heading", content: "Comment rédiger une chronologie claire des faits" },
      { type: "paragraph", content: "Sur une feuille ou un document, listez les événements dans l'ordre chronologique, du plus ancien au plus récent. Pour chaque événement : la date, ce qui s'est passé (une phrase), et le document qui le prouve. Cette chronologie permet à l'avocat de comprendre votre situation en 5 minutes." },
      { type: "heading", content: "Les questions à poser à votre avocat (et celles qu'il vous posera)" },
      { type: "paragraph", content: "Préparez vos questions à l'avance : Quelles sont mes chances d'obtenir gain de cause ? Combien de temps va durer la procédure ? Quel est le budget total estimé ? Quelles sont les alternatives à une procédure judiciaire ? Quels sont les risques si je perds ? L'avocat vous posera lui aussi des questions, soyez prêt à répondre sur vos objectifs, vos contraintes budgétaires, et votre historique." },
      { type: "heading", content: "Budget : combien coûte une consultation et une procédure" },
      { type: "paragraph", content: "Une première consultation coûte généralement entre 100 et 300€. Une procédure complète peut aller de 2 000 à 15 000€ selon la complexité et la durée. Demandez un devis écrit avant de vous engager. Certains avocats proposent un paiement échelonné. Vérifiez si votre assurance protection juridique couvre le litige." },
      { type: "tip", content: "Avant d'aller voir un avocat, utilisez le Bouclier Légal WTF (gratuit) pour analyser votre contrat et identifier les clauses problématiques. Vous arriverez au rendez-vous avec une première analyse, ce qui fera gagner du temps à tout le monde." },
    ],
    cta: {
      title: "Analysez votre contrat avant d'aller voir un avocat",
      description: "Le Bouclier Légal identifie les clauses problématiques en 5 minutes. Gratuit, sans inscription.",
      buttonLabel: "Analyser mon contrat",
      buttonHref: "/protection",
    },
  },
  {
    slug: "pourquoi-halo-refuse-promesses-richesse-rapide",
    title: "Pourquoi WTF refuse les promesses de richesse rapide",
    description: "Dans un secteur où les promesses de gains mirobolants sont monnaie courante, WTF revendique une approche sobre et réaliste du management de créateur.",
    category: "image-strategie",
    date: "2026-06-01",
    readingTime: 8,
    author: "Équipe WTF",
    content: [
      { type: "heading", content: "Le problème des promesses de richesse rapide dans l'industrie du management créateur" },
      { type: "paragraph", content: "Parcourez les publicités des agences de management créateur : « Gagnez 10 000€ par mois en 3 mois », « Devenez top 1% sur OnlyFans », « Multipliez vos revenus par 10 ». Ces promesses sont séduisantes, mais elles reposent sur un postulat trompeur : que le succès d'un créateur est garanti et rapide." },
      { type: "paragraph", content: "La réalité : construire une activité de créateur rentable prend du temps. Cela demande de la constance, de la stratégie, et une compréhension fine de son audience. Les créateurs qui réussissent sur la durée sont ceux qui ont construit des fondations solides, pas ceux qui ont suivi une recette miracle." },
      { type: "heading", content: "Pourquoi ces promesses attirent mais détruisent la confiance" },
      { type: "paragraph", content: "Une promesse de richesse rapide fonctionne comme un appât : elle attire les créateurs qui doutent, qui galèrent, qui cherchent une solution. Mais quand la promesse n'est pas tenue, et elle ne l'est presque jamais, la confiance est brisée. Le créateur se sent floué, l'agence perd sa crédibilité, et l'industrie tout entière pâtit de cette défiance." },
      { type: "heading", content: "L'approche WTF : poser des fondations solides" },
      { type: "paragraph", content: "Notre approche est différente. Nous ne vous promettons pas un revenu. Nous vous donnons des outils, des analyses, une structure. Nous vous aidons à comprendre votre audience, à protéger vos comptes, à optimiser votre contenu. La croissance vient de votre travail, pas de nos promesses. Nous sommes un accélérateur, pas une baguette magique." },
      { type: "heading", content: "Ce que signifie construire une activité durable de créateur" },
      { type: "list", content: "Les piliers d'une activité durable :", items: [
        "Une image de marque cohérente et reconnaissable",
        "Une stratégie de contenu planifiée, pas improvisée",
        "Des comptes sécurisés et protégés",
        "Des contrats clairs avec l'agence, les marques et les collaborateurs",
        "Une diversification des sources de revenus (abonnements, PPV, partenariats)",
        "Une gestion financière rigoureuse (suivi des revenus, des commissions, de la fiscalité)",
      ]},
      { type: "heading", content: "Transparence sur les revenus réalistes par département et par profil" },
      { type: "paragraph", content: "Les revenus varient considérablement selon le département, l'ancienneté, la stratégie et l'engagement. Un créateur Glamour Premium établi ne gagne pas la même chose qu'un créateur Sport/Fitness qui débute. Nous préférons vous aider à comprendre où vous vous situez et comment progresser, plutôt que de vous vendre un classement fictif." },
      { type: "quote", content: "Notre engagement n'est pas de vous rendre riche en 3 mois. Il est de vous donner les moyens de construire une activité qui vous ressemble et qui dure." },
    ],
    cta: {
      title: "Découvrez l'approche WTF",
      description: "Pas de promesses. Des outils, une structure, une équipe. Le reste vient de vous.",
      buttonLabel: "Qui sommes-nous",
      buttonHref: "/qui-sommes-nous",
    },
  },
];
