import type { TeamMember, AuditLogEntry } from "./types";

export const teamMembers: TeamMember[] = [
  {
    id: "u-1",
    email: "thomas@halotalent.com",
    full_name: "Thomas Delacroix",
    role: "owner",
    avatar_url: null,
    assigned_creators: [
      { id: "c1", name: "Clara W." }, { id: "c2", name: "Marc T." },
      { id: "c3", name: "Léa R." }, { id: "c4", name: "Inès D." },
      { id: "c5", name: "Alex M." }, { id: "c6", name: "Emma V." }, { id: "c7", name: "Hugo P." },
    ],
    last_login: "2026-06-08T09:30:00Z",
    active: true,
    custom_permissions: {},
    invited_at: "2024-07-01T00:00:00Z",
    created_at: "2024-07-01T00:00:00Z",
  },
  {
    id: "u-2",
    email: "claire@halotalent.com",
    full_name: "Claire Moreau",
    role: "admin",
    avatar_url: null,
    assigned_creators: [
      { id: "c1", name: "Clara W." }, { id: "c3", name: "Léa R." },
      { id: "c6", name: "Emma V." },
    ],
    last_login: "2026-06-08T08:15:00Z",
    active: true,
    custom_permissions: {},
    invited_at: "2024-09-15T10:00:00Z",
    created_at: "2024-09-15T10:00:00Z",
  },
  {
    id: "u-3",
    email: "alexandre@halotalent.com",
    full_name: "Alexandre Petit",
    role: "admin",
    avatar_url: null,
    assigned_creators: [
      { id: "c2", name: "Marc T." }, { id: "c4", name: "Inès D." },
      { id: "c5", name: "Alex M." }, { id: "c7", name: "Hugo P." },
    ],
    last_login: "2026-06-07T14:30:00Z",
    active: true,
    custom_permissions: {},
    invited_at: "2024-10-01T10:00:00Z",
    created_at: "2024-10-01T10:00:00Z",
  },
  {
    id: "u-4",
    email: "sophie@halotalent.com",
    full_name: "Sophie Laurent",
    role: "manager",
    avatar_url: null,
    assigned_creators: [
      { id: "c1", name: "Clara W." }, { id: "c3", name: "Léa R." },
    ],
    last_login: "2026-06-07T16:45:00Z",
    active: true,
    custom_permissions: {},
    invited_at: "2025-01-10T10:00:00Z",
    created_at: "2025-01-10T10:00:00Z",
  },
  {
    id: "u-5",
    email: "julien@halotalent.com",
    full_name: "Julien Bernard",
    role: "manager",
    avatar_url: null,
    assigned_creators: [
      { id: "c2", name: "Marc T." }, { id: "c5", name: "Alex M." },
    ],
    last_login: "2026-06-06T11:20:00Z",
    active: true,
    custom_permissions: {},
    invited_at: "2025-03-05T10:00:00Z",
    created_at: "2025-03-05T10:00:00Z",
  },
  {
    id: "u-6",
    email: "marine@halotalent.com",
    full_name: "Marine Dubois",
    role: "assistant",
    avatar_url: null,
    assigned_creators: [
      { id: "c4", name: "Inès D." },
    ],
    last_login: "2026-06-05T10:00:00Z",
    active: true,
    custom_permissions: {},
    invited_at: "2025-06-01T10:00:00Z",
    created_at: "2025-06-01T10:00:00Z",
  },
  {
    id: "u-7",
    email: "lucas@halotalent.com",
    full_name: "Lucas Rousseau",
    role: "assistant",
    avatar_url: null,
    assigned_creators: [
      { id: "c6", name: "Emma V." }, { id: "c7", name: "Hugo P." },
    ],
    last_login: null,
    active: false,
    custom_permissions: {},
    invited_at: "2026-04-01T10:00:00Z",
    created_at: "2026-04-01T10:00:00Z",
  },
];

export const auditLogs: AuditLogEntry[] = [
  { id: "log-1", actor: "Thomas Delacroix", action: "invite_member", target: "Sophie Laurent", details: "Invitation envoyée en tant que manager", created_at: "2026-06-01T10:00:00Z" },
  { id: "log-2", actor: "Claire Moreau", action: "approve_application", target: "Nouveau créateur #24", details: "Candidature approuvée - département Music", created_at: "2026-06-02T14:30:00Z" },
  { id: "log-3", actor: "Alexandre Petit", action: "edit_contract", target: "Marc T.", details: "Taux de commission mis à jour 15% → 12%", created_at: "2026-06-03T09:15:00Z" },
  { id: "log-4", actor: "Thomas Delacroix", action: "deactivate_member", target: "Lucas Rousseau", details: "Compte désactivé - fin de période d'essai", created_at: "2026-06-04T11:00:00Z" },
  { id: "log-5", actor: "Sophie Laurent", action: "send_message", target: "Clara W.", details: "Message envoyé : briefing campagne été", created_at: "2026-06-05T16:00:00Z" },
  { id: "log-6", actor: "Claire Moreau", action: "export_data", target: "Analytics Q2", details: "Export CSV des revenus Q2 2026", created_at: "2026-06-06T08:00:00Z" },
  { id: "log-7", actor: "Thomas Delacroix", action: "manage_permissions", target: "Rôle Assistant", details: "Permission send_messages activée pour le rôle assistant", created_at: "2026-06-07T12:00:00Z" },
  { id: "log-8", actor: "Julien Bernard", action: "edit_creator", target: "Alex M.", details: "Bio mise à jour", created_at: "2026-06-07T17:30:00Z" },
];
