import type { Payout } from "./types";

export const payouts: Payout[] = [
  {
    id: "po-1",
    creator_id: "c4",
    creator_name: "Inès D.",
    creator_avatar: null,
    department: "Digital Creators",
    amount: 5420,
    period: "Mai 2026",
    method: "stripe",
    scheduled_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3).toISOString(),
    status: "validated",
    validated_by: "Marc A.",
    validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    double_validated_by: null,
    double_validated_at: null,
    executed_at: null,
    error_message: null,
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: "po-2",
    creator_id: "c4",
    creator_name: "Inès D.",
    creator_avatar: null,
    department: "Digital Creators",
    amount: 6200,
    period: "Juin 2026",
    method: "stripe",
    scheduled_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10).toISOString(),
    status: "pending",
    validated_by: null,
    validated_at: null,
    double_validated_by: null,
    double_validated_at: null,
    executed_at: null,
    error_message: null,
    notes: "Paiement >5000€, double validation requise",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "po-3",
    creator_id: "c6",
    creator_name: "Emma V.",
    creator_avatar: null,
    department: "Music & Performing Arts",
    amount: 4800,
    period: "Mai 2026",
    method: "stripe",
    scheduled_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5).toISOString(),
    status: "pending",
    validated_by: null,
    validated_at: null,
    double_validated_by: null,
    double_validated_at: null,
    executed_at: null,
    error_message: null,
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: "po-4",
    creator_id: "c6",
    creator_name: "Emma V.",
    creator_avatar: null,
    department: "Music & Performing Arts",
    amount: 4800,
    period: "Avril 2026",
    method: "stripe",
    scheduled_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
    status: "completed",
    validated_by: "Sophie L.",
    validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 28).toISOString(),
    double_validated_by: null,
    double_validated_at: null,
    executed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 24).toISOString(),
    error_message: null,
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
  },
  {
    id: "po-5",
    creator_id: "c2",
    creator_name: "Marc T.",
    creator_avatar: null,
    department: "Digital Creators",
    amount: 3800,
    period: "Mai 2026",
    method: "wire",
    scheduled_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(),
    status: "pending",
    validated_by: null,
    validated_at: null,
    double_validated_by: null,
    double_validated_at: null,
    executed_at: null,
    error_message: null,
    notes: "Virement bancaire international",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "po-6",
    creator_id: "c2",
    creator_name: "Marc T.",
    creator_avatar: null,
    department: "Digital Creators",
    amount: 3700,
    period: "Avril 2026",
    method: "wire",
    scheduled_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    status: "completed",
    validated_by: "Marc A.",
    validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
    double_validated_by: null,
    double_validated_at: null,
    executed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 19).toISOString(),
    error_message: null,
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
  },
  {
    id: "po-7",
    creator_id: "c1",
    creator_name: "Clara W.",
    creator_avatar: null,
    department: "Digital Creators",
    amount: 2100,
    period: "Mai 2026",
    method: "stripe",
    scheduled_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 4).toISOString(),
    status: "pending",
    validated_by: null,
    validated_at: null,
    double_validated_by: null,
    double_validated_at: null,
    executed_at: null,
    error_message: null,
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
  },
  {
    id: "po-8",
    creator_id: "c1",
    creator_name: "Clara W.",
    creator_avatar: null,
    department: "Digital Creators",
    amount: 2000,
    period: "Avril 2026",
    method: "stripe",
    scheduled_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 22).toISOString(),
    status: "completed",
    validated_by: "Marc A.",
    validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 27).toISOString(),
    double_validated_by: null,
    double_validated_at: null,
    executed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 21).toISOString(),
    error_message: null,
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 38).toISOString(),
  },
  {
    id: "po-9",
    creator_id: "c3",
    creator_name: "Léa R.",
    creator_avatar: null,
    department: "Music & Performing Arts",
    amount: 1400,
    period: "Mai 2026",
    method: "stripe",
    scheduled_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 6).toISOString(),
    status: "pending",
    validated_by: null,
    validated_at: null,
    double_validated_by: null,
    double_validated_at: null,
    executed_at: null,
    error_message: null,
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "po-10",
    creator_id: "c3",
    creator_name: "Léa R.",
    creator_avatar: null,
    department: "Music & Performing Arts",
    amount: 1300,
    period: "Avril 2026",
    method: "stripe",
    scheduled_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
    status: "completed",
    validated_by: "Sophie L.",
    validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 23).toISOString(),
    double_validated_by: null,
    double_validated_at: null,
    executed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 17).toISOString(),
    error_message: null,
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
  },
  {
    id: "po-11",
    creator_id: "c7",
    creator_name: "Hugo P.",
    creator_avatar: null,
    department: "Business & Thought Leadership",
    amount: 1100,
    period: "Mai 2026",
    method: "wire",
    scheduled_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 8).toISOString(),
    status: "pending",
    validated_by: null,
    validated_at: null,
    double_validated_by: null,
    double_validated_at: null,
    executed_at: null,
    error_message: null,
    notes: "Virement SEPA",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "po-12",
    creator_id: "c7",
    creator_name: "Hugo P.",
    creator_avatar: null,
    department: "Business & Thought Leadership",
    amount: 1000,
    period: "Avril 2026",
    method: "wire",
    scheduled_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    status: "completed",
    validated_by: "Clara W.",
    validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    double_validated_by: null,
    double_validated_at: null,
    executed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    error_message: null,
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
  },
  {
    id: "po-13",
    creator_id: "c5",
    creator_name: "Alex M.",
    creator_avatar: null,
    department: "Sport & Lifestyle",
    amount: 500,
    period: "Mai 2026",
    method: "stripe",
    scheduled_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    status: "error",
    validated_by: "Thomas R.",
    validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    double_validated_by: null,
    double_validated_at: null,
    executed_at: null,
    error_message: "Compte Stripe non connecté, onboarding requis",
    notes: "Relancer Alex pour finaliser Stripe",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: "po-14",
    creator_id: "c5",
    creator_name: "Alex M.",
    creator_avatar: null,
    department: "Sport & Lifestyle",
    amount: 480,
    period: "Avril 2026",
    method: "stripe",
    scheduled_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 28).toISOString(),
    status: "error",
    validated_by: "Thomas R.",
    validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 32).toISOString(),
    double_validated_by: null,
    double_validated_at: null,
    executed_at: null,
    error_message: "Échec du virement, coordonnées bancaires invalides",
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
  },
  {
    id: "po-15",
    creator_id: "c4",
    creator_name: "Inès D.",
    creator_avatar: null,
    department: "Digital Creators",
    amount: 5800,
    period: "Avril 2026",
    method: "stripe",
    scheduled_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 21).toISOString(),
    status: "completed",
    validated_by: "Marc A.",
    validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 26).toISOString(),
    double_validated_by: "Sophie L.",
    double_validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
    executed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    error_message: null,
    notes: "Double validation effectuée (>5000€)",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
  },
  {
    id: "po-16",
    creator_id: "c1",
    creator_name: "Clara W.",
    creator_avatar: null,
    department: "Digital Creators",
    amount: 1950,
    period: "Mars 2026",
    method: "other",
    scheduled_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 50).toISOString(),
    status: "completed",
    validated_by: "Marc A.",
    validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 55).toISOString(),
    double_validated_by: null,
    double_validated_at: null,
    executed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 48).toISOString(),
    error_message: null,
    notes: "Paiement manuel via virement bancaire",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 65).toISOString(),
  },
  {
    id: "po-17",
    creator_id: "c2",
    creator_name: "Marc T.",
    creator_avatar: null,
    department: "Digital Creators",
    amount: 3500,
    period: "Mars 2026",
    method: "stripe",
    scheduled_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    status: "completed",
    validated_by: "Marc A.",
    validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 50).toISOString(),
    double_validated_by: null,
    double_validated_at: null,
    executed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 43).toISOString(),
    error_message: null,
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
  },
  {
    id: "po-18",
    creator_id: "c6",
    creator_name: "Emma V.",
    creator_avatar: null,
    department: "Music & Performing Arts",
    amount: 4500,
    period: "Mars 2026",
    method: "stripe",
    scheduled_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 42).toISOString(),
    status: "completed",
    validated_by: "Sophie L.",
    validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 48).toISOString(),
    double_validated_by: null,
    double_validated_at: null,
    executed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    error_message: null,
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 55).toISOString(),
  },
];
