// ─── Bouclier Légal — 6 catégories de clauses ───────────
// Données complètes avec arguments juridiques et reformulations

import type { ClauseGroup } from "./types";

export const CLAUSE_GROUPS: ClauseGroup[] = [
  {
    category: "account_control",
    label: "Contrôle du compte",
    icon: "🔐",
    severityLabel: "haute",
    clauses: [
      {
        id: "account_credentials",
        category: "account_control",
        label: "L'agence a les identifiants de mon compte",
        description: "L'agence détient vos identifiants de connexion et peut accéder à votre compte à tout moment.",
        severity: 5,
        legalArgument: "La délégation d'identifiants viole les CGU de la plupart des plateformes (OnlyFans clause 3.2, MYM article 5). Vous êtes responsable de toute action effectuée depuis votre compte, même par l'agence.",
        recommendedAction: "Exigez que l'agence utilise un système de délégation de compte officiel (si la plateforme le permet) ou cessez de partager vos identifiants.",
        legalRef: "OnlyFans CGU 3.2, MYM Art. 5 — Interdiction de partage de compte",
        sanaReformulation: "Le créateur conserve l'exclusivité de ses identifiants. L'agence dispose d'un accès via un outil de gestion agréé par la plateforme, sans connaître le mot de passe.",
      },
      {
        id: "post_without_validation",
        label: "L'agence peut poster sans ma validation",
        description: "L'agence publie du contenu sur votre compte sans votre approbation préalable.",
        severity: 4,
        legalArgument: "Vous êtes juridiquement responsable de tout contenu publié sous votre identité. Si l'agence publie sans validation, vous ne pouvez pas contrôler les risques d'atteinte à votre image, de violation de CGU ou de droit à l'image.",
        recommendedAction: "Exigez une clause de validation préalable écrite pour toute publication.",
        sanaReformulation: "Tout contenu publié sur le compte du créateur doit être approuvé par écrit au préalable, avec un délai de validation ne pouvant excéder 24 heures.",
      },
      {
        id: "password_locked",
        label: "Je ne peux pas changer mon mot de passe",
        description: "Le contrat vous interdit de modifier le mot de passe ou les accès à votre compte.",
        severity: 5,
        legalArgument: "Cette clause est abusive car elle vous prive du contrôle élémentaire de votre compte et de votre identité numérique. Elle pourrait être annulée par un tribunal comme clause abusive au sens de l'article L.212-1 du Code de la consommation.",
        recommendedAction: "Refusez cette clause. Vous devez toujours pouvoir reprendre le contrôle de votre compte.",
        legalRef: "Art. L.212-1 Code de la consommation — Clauses abusives",
        sanaReformulation: "Le créateur conserve la maîtrise totale de ses accès et peut modifier ses identifiants à tout moment, sous réserve d'en informer l'agence.",
      },
      {
        id: "dm_access",
        label: "L'agence a accès à mes DM privés sans mon accord",
        description: "Vos messages privés avec vos fans sont consultés par l'agence sans votre consentement explicite.",
        severity: 4,
        legalArgument: "Les DM privés contiennent des données personnelles et des conversations confidentielles. Leur accès sans consentement explicite peut violer le RGPD (Règlement Général sur la Protection des Données).",
        recommendedAction: "Exigez une clause de confidentialité et un accord explicite sur le périmètre d'accès aux DM.",
        legalRef: "RGPD Art. 5 — Principe de minimisation des données",
        sanaReformulation: "L'agence peut accéder aux DM dans le seul cadre de la gestion des abonnés, après consentement écrit du créateur. Les conversations à caractère personnel sont exclues.",
      },
    ],
  },
  {
    category: "financial",
    label: "Clauses financières",
    icon: "💰",
    severityLabel: "haute",
    clauses: [
      {
        id: "commission_over_50",
        label: "Commission supérieure à 50%",
        description: "L'agence prélève plus de la moitié de vos revenus.",
        severity: 5,
        legalArgument: "Une commission supérieure à 50% est disproportionnée par rapport aux services fournis dans la plupart des cas. La moyenne du marché OFM se situe entre 20% et 35%. Une commission excessive peut être requalifiée en clause abusive.",
        recommendedAction: "Négociez une commission entre 15% et 35% selon les services inclus.",
        legalRef: "Art. L.442-1 Code de commerce — Déséquilibre significatif",
        sanaReformulation: "La rémunération de l'agence est fixée à [X]% du revenu brut généré, avec un plafond dégressif au-delà de [montant] € de revenus mensuels.",
      },
      {
        id: "commission_after_contract",
        label: "Commission sur les revenus même après la fin du contrat",
        description: "L'agence continue à percevoir une commission sur vos revenus après la rupture du contrat.",
        severity: 5,
        legalArgument: "Cette clause crée une obligation perpétuelle qui peut être annulée comme clause abusive. Le travail de l'agence cesse à la fin du contrat, il n'est pas légitime de continuer à prélever une commission sur des revenus futurs sans service correspondant.",
        recommendedAction: "Refusez catégoriquement. Maximum : commission dégressive sur 3-6 mois post-contrat si l'agence a apporté des abonnés de longue durée.",
        legalRef: "Art. L.212-1 Code de la consommation — Clauses abusives ; Jurisprudence constante",
        sanaReformulation: "À la fin du contrat, aucune commission n'est due sur les revenus futurs du créateur. Les commissions en cours sont versées jusqu'à la date effective de rupture.",
      },
      {
        id: "hidden_fees",
        label: "Frais cachés ou 'frais de setup'",
        description: "Des frais non mentionnés initialement sont facturés (frais d'inscription, de dossier, de formation).",
        severity: 4,
        legalArgument: "L'absence de transparence sur les frais viole l'obligation d'information précontractuelle (Art. L.111-1 Code de la consommation). Les frais cachés sont illégaux et peuvent donner lieu à des dommages et intérêts.",
        recommendedAction: "Exigez un devis détaillé et transparent avant tout engagement. Refusez tout frais non justifié.",
        legalRef: "Art. L.111-1 et L.113-3 Code de la consommation",
        sanaReformulation: "Tous les frais sont détaillés dans une annexe transparente au contrat. Aucun frais caché ou frais de gestion supplémentaire ne peut être facturé sans accord écrit préalable.",
      },
      {
        id: "no_commission_transparency",
        label: "Pas de transparence sur le calcul des commissions",
        description: "Le contrat ne précise pas comment les commissions sont calculées ni sur quelle assiette.",
        severity: 3,
        legalArgument: "L'obligation de transparence est un principe fondamental du droit des contrats. Sans mode de calcul clair, vous ne pouvez pas vérifier que les montants prélevés sont corrects.",
        recommendedAction: "Exigez un détail mensuel des revenus bruts, commissions et revenus nets.",
        sanaReformulation: "Chaque mois, l'agence fournit un rapport détaillé indiquant : revenu brut par plateforme, montant des commissions, revenu net versé, avec accès à un outil de suivi en temps réel.",
      },
      {
        id: "payment_withholding",
        label: "Retenue de paiements sans motif clair",
        description: "L'agence peut retenir vos paiements sans justification précise.",
        severity: 4,
        legalArgument: "La retenue unilatérale de paiements sans motif valable constitue une violation de l'obligation de payer et peut être requalifiée en abus de droit.",
        recommendedAction: "Exigez que toute retenue soit motivée par écrit et limitée dans le temps.",
        sanaReformulation: "Les paiements sont versés avant le 10 du mois suivant. Toute retenue doit être motivée par écrit et ne peut excéder 15 jours ouvrés. Passé ce délai, des intérêts de retard sont dus.",
      },
    ],
  },
  {
    category: "contractual",
    label: "Clauses contractuelles",
    icon: "📄",
    severityLabel: "moyenne-haute",
    clauses: [
      {
        id: "commitment_over_6_months",
        label: "Engagement supérieur à 6 mois",
        description: "Le contrat vous lie pour une durée supérieure à 6 mois sans possibilité de sortie anticipée.",
        severity: 3,
        legalArgument: "Un engagement de longue durée sans clause de sortie peut constituer un déséquilibre significatif. La durée d'engagement moyenne dans le secteur OFM est de 3 à 6 mois.",
        recommendedAction: "Limitez l'engagement initial à 3-6 mois avec tacite reconduction possible mais révocable.",
        sanaReformulation: "Le contrat est conclu pour une durée de 3 mois, renouvelable par tacite reconduction. Chaque partie peut résilier avec un préavis de 30 jours.",
      },
      {
        id: "early_exit_penalty",
        label: "Pénalité de sortie anticipée",
        description: "Des pénalités financières sont prévues si vous quittez le contrat avant son terme.",
        severity: 4,
        legalArgument: "Les pénalités de sortie disproportionnées (ex: 6 mois de commissions) sont souvent annulées par les tribunaux comme clauses abusives (Art. L.212-1 Code conso).",
        recommendedAction: "Refusez ou négociez une pénalité dégressive et plafonnée à 1 mois de commission.",
        legalRef: "Art. L.212-1 Code de la consommation",
        sanaReformulation: "En cas de résiliation anticipée sans motif grave, une indemnité correspondant à 30 jours de commission moyenne est due. Aucune pénalité n'est due en cas de manquement grave de l'agence.",
      },
      {
        id: "auto_renewal",
        label: "Renouvellement automatique sans notification",
        description: "Le contrat se renouvelle automatiquement sans que vous en soyez informé.",
        severity: 3,
        legalArgument: "Le renouvellement automatique sans notification préalable est encadré par la loi : le professionnel doit vous informer entre 3 mois et 1 mois avant la fin de la période de reconduction.",
        recommendedAction: "Exigez une clause de notification de renouvellement avec accusé de réception 2 mois avant l'échéance.",
        legalRef: "Art. L.215-1 Code de la consommation",
        sanaReformulation: "Le contrat est renouvelé par tacite reconduction par périodes de 3 mois. L'agence notifie le créateur 60 jours avant l'échéance par email avec accusé de réception. Le créateur peut s'opposer au renouvellement jusqu'à 30 jours avant l'échéance.",
      },
      {
        id: "non_compete",
        label: "Clause de non-concurrence après la fin du contrat",
        description: "Le contrat vous interdit de travailler avec d'autres agences ou plateformes après la fin du contrat.",
        severity: 4,
        legalArgument: "Une clause de non-concurrence doit être limitée dans le temps, l'espace et la nature de l'activité, et impérativement compensée financièrement (contrepartie financière). Sans contrepartie, elle est nulle.",
        recommendedAction: "Exigez une contrepartie financière d'au moins 30% de votre rémunération moyenne. Limitez la durée à 3 mois maximum.",
        legalRef: "Art. L.1121-1 Code du travail (principe général)",
        sanaReformulation: "Une clause de non-concurrence de 3 mois maximum, limitée aux plateformes gérées par l'agence, avec une contrepartie financière de [X]€ par mois.",
      },
    ],
  },
  {
    category: "content_rights",
    label: "Droits de contenu",
    icon: "📸",
    severityLabel: "haute",
    clauses: [
      {
        id: "agency_holds_rights",
        label: "L'agence détient les droits sur mon contenu",
        description: "Le contrat stipule que l'agence est propriétaire des droits sur les photos, vidéos et autres contenus que vous produisez.",
        severity: 5,
        legalArgument: "La cession des droits d'auteur sans limite de durée, d'usage ou de territoire est abusive. En droit français, la cession des droits d'auteur doit être limitée et précisément décrite (Art. L.131-3 Code de la propriété intellectuelle).",
        recommendedAction: "N'acceptez jamais de céder vos droits d'auteur. Accordez uniquement une licence d'utilisation limitée dans le temps et l'objet.",
        legalRef: "Art. L.131-3 Code de la propriété intellectuelle",
        sanaReformulation: "Le créateur conserve l'intégralité de ses droits d'auteur. L'agence bénéficie d'une licence non exclusive, limitée à la durée du contrat, pour l'exploitation commerciale sur les plateformes désignées.",
      },
      {
        id: "post_contract_image_use",
        label: "L'agence peut utiliser mon image après la fin du contrat",
        description: "Votre image et votre contenu peuvent continuer à être exploités par l'agence après la rupture.",
        severity: 5,
        legalArgument: "L'exploitation de l'image d'une personne sans son consentement après la fin de la relation contractuelle constitue une atteinte au droit à l'image (Art. 9 Code civil).",
        recommendedAction: "Exigez la suppression de tout votre contenu des supports de l'agence à la fin du contrat.",
        legalRef: "Art. 9 Code civil — Droit au respect de la vie privée",
        sanaReformulation: "À la fin du contrat, l'agence cesse toute utilisation du contenu et de l'image du créateur. Tous les contenus présents sur les supports de l'agence sont supprimés sous 15 jours.",
      },
      {
        id: "no_content_return",
        label: "Pas de clause de restitution du contenu à la fin",
        description: "Le contrat ne prévoit pas que l'agence vous restitue vos contenus à la fin de la collaboration.",
        severity: 3,
        legalArgument: "Les contenus que vous avez créés vous appartiennent. L'absence de clause de restitution peut vous priver de votre travail passé.",
        recommendedAction: "Exigez une clause de restitution avec inventaire et support de transfert définis.",
        sanaReformulation: "À la fin du contrat, l'agence restitue au créateur l'intégralité des fichiers originaux (photos, vidéos, textes) sous format numérique, dans un délai de 15 jours, sur le support de son choix.",
      },
    ],
  },
  {
    category: "communication",
    label: "Communication",
    icon: "🔇",
    severityLabel: "moyenne",
    clauses: [
      {
        id: "no_other_agencies",
        label: "Interdiction de communiquer avec d'autres agences",
        description: "Le contrat vous interdit d'échanger ou de négocier avec d'autres agences.",
        severity: 3,
        legalArgument: "Cette clause peut être considérée comme une entrave à la liberté d'entreprendre et au libre choix de son partenaire commercial.",
        recommendedAction: "Refusez toute clause d'exclusivité de négociation. Vous devez pouvoir explorer d'autres options.",
        sanaReformulation: "Le créateur s'engage à informer l'agence en cas de démarchage par une autre agence mais conserve le droit d'étudier d'autres propositions.",
      },
      {
        id: "total_exclusivity",
        label: "Obligation d'exclusivité totale sur toutes les plateformes",
        description: "L'agence exige l'exclusivité sur l'ensemble de vos activités et plateformes.",
        severity: 3,
        legalArgument: "L'exclusivité totale peut être légitime si elle est définie précisément (plateformes, durée, services). L'exclusivité générale et indéterminée est abusive.",
        recommendedAction: "Limitez l'exclusivité à des plateformes spécifiques et des types de services précis.",
        sanaReformulation: "L'exclusivité est limitée aux plateformes suivantes : [liste]. Le créateur conserve le droit de développer son activité sur d'autres plateformes ou via d'autres canaux.",
      },
      {
        id: "agency_communicates_without_validation",
        label: "L'agence communique avec mes fans sans ma validation",
        description: "L'agence peut envoyer des messages à vos fans en votre nom sans votre approbation.",
        severity: 3,
        legalArgument: "Les communications avec vos fans engagent votre responsabilité et votre image. Sans contrôle, vous ne pouvez pas garantir la qualité et l'adéquation des échanges.",
        recommendedAction: "Exigez une validation préalable des templates de messages et un accès en lecture à tous les échanges.",
        sanaReformulation: "L'agence gère les échanges avec les abonnés selon des templates validés par écrit par le créateur. Le créateur a accès en lecture à l'ensemble des conversations.",
      },
    ],
  },
  {
    category: "psychological",
    label: "Clauses psychologiques",
    icon: "🧠",
    severityLabel: "moyenne",
    clauses: [
      {
        id: "unrealistic_goals",
        label: "Objectifs de publication irréalistes avec pénalités",
        description: "Des quotas de publication très élevés sont imposés, avec des pénalités en cas de non-respect.",
        severity: 3,
        legalArgument: "Des objectifs manifestement irréalistes accompagnés de pénalités peuvent être requalifiés en clause abusive car ils créent un déséquilibre significatif entre les droits et obligations des parties.",
        recommendedAction: "Négociez des objectifs réalistes basés sur votre production moyenne, sans pénalités disproportionnées.",
        sanaReformulation: "Le créateur s'engage sur un volume de [X] publications par semaine, révisable trimestriellement. Aucune pénalité n'est due en cas de non-atteinte, mais un plan d'action est mis en place.",
      },
      {
        id: "availability_24_7",
        label: "Obligation de disponibilité 24/7",
        description: "Le contrat exige que vous soyez joignable et disponible à tout moment.",
        severity: 4,
        legalArgument: "L'obligation de disponibilité permanente est contraire au droit au repos et à la déconnexion. Elle peut être considérée comme abusive et attentatoire aux droits fondamentaux.",
        recommendedAction: "Définissez des plages horaires de disponibilité et un droit à la déconnexion.",
        legalRef: "Art. L.2242-8 Code du travail — Droit à la déconnexion (principe général)",
        sanaReformulation: "Le créateur est disponible selon des plages horaires définies d'un commun accord, avec un droit à la déconnexion garanti. Les urgences sont gérées via un protocole écrit.",
      },
      {
        id: "physical_restrictions",
        label: "Clause d'image imposant des restrictions physiques",
        description: "Le contrat vous impose des restrictions sur votre apparence physique, poids, ou transformations corporelles.",
        severity: 3,
        legalArgument: "Les clauses imposant des restrictions physiques peuvent porter atteinte à l'intégrité physique et à la liberté personnelle. Elles sont potentiellement nulles si elles excèdent ce qui est raisonnablement nécessaire à l'activité.",
        recommendedAction: "Refusez toute clause portant sur votre apparence physique. Acceptez une charte stylistique si nécessaire.",
        sanaReformulation: "Le créateur et l'agence définissent ensemble une ligne éditoriale et stylistique. Le créateur conserve le dernier mot sur son apparence et les transformations physiques.",
      },
    ],
  },
];
