import type { CommissionAdjustment } from "./types";

export const commissionAdjustments: CommissionAdjustment[] = [
  {
    id: "adj-1",
    creator_id: "c4",
    creator_name: "Inès D.",
    month: "Mai 2026",
    original_commission_eur: 4800,
    adjusted_commission_eur: 4200,
    difference: -600,
    reason: "Remise commerciale, engagement pluriannuel",
    justification: "Inès a signé un engagement de 2 ans supplémentaires. Réduction de commission de 15% à 12% négociée en échange.",
    status: "validated",
    requested_by: "Marc A.",
    validated_by: "Sophie L.",
    validated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: "adj-2",
    creator_id: "c1",
    creator_name: "Clara W.",
    month: "Mai 2026",
    original_commission_eur: 2100,
    adjusted_commission_eur: 1900,
    difference: -200,
    reason: "Erreur de calcul",
    justification: "Double facturation sur une collaboration marque détectée. Ajustement manuel nécessaire.",
    status: "pending",
    requested_by: "Marc A.",
    validated_by: null,
    validated_at: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "adj-3",
    creator_id: "c2",
    creator_name: "Marc T.",
    month: "Juin 2026",
    original_commission_eur: 3800,
    adjusted_commission_eur: 5500,
    difference: 1700,
    reason: "Avenant contrat, nouveau palier",
    justification: "Marc est passé au palier Elite avec un contrat spécial à 8%. L'ajustement reflète le nouveau taux rétroactif sur 3 mois.",
    status: "pending",
    requested_by: "Marc A.",
    validated_by: null,
    validated_at: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
];
