import type { VideoTemplate, StickerDef } from "./editor-types";

export const VIDEO_TEMPLATES: VideoTemplate[] = [
  {
    id: "slideshow-musical",
    name: "Slideshow musical",
    description: "Montage photos + musique de fond, transition fluide",
    duration: 15,
    aspectRatio: "9:16",
    icon: "🎵",
    compatibleDna: true,
    scenes: [
      { type: "text", startFrame: 0, duration: 30, props: { text: "📷 Mes moments", x: 50, y: 50, fontSize: 48, color: "var(--text-primary)", animation: "fadeIn" } },
      { type: "image", startFrame: 30, duration: 90, props: { x: 50, y: 50, width: 100, height: 100, animation: "fadeIn" }, placeholder: { label: "Photo 1", accept: "image/*" } },
      { type: "image", startFrame: 120, duration: 90, props: { x: 50, y: 50, width: 100, height: 100, animation: "fadeIn" }, placeholder: { label: "Photo 2", accept: "image/*" } },
      { type: "image", startFrame: 210, duration: 90, props: { x: 50, y: 50, width: 100, height: 100, animation: "fadeIn" }, placeholder: { label: "Photo 3", accept: "image/*" } },
      { type: "text", startFrame: 300, duration: 90, props: { text: "✨ Merci d'être passé", x: 50, y: 50, fontSize: 36, color: "var(--accent)", animation: "slideUp" } },
    ],
  },
  {
    id: "outfit-reveal",
    name: "Outfit reveal",
    description: "Template mode populaire : 3 tenues en transition rapide",
    duration: 12,
    aspectRatio: "9:16",
    icon: "👗",
    compatibleDna: true,
    scenes: [
      { type: "text", startFrame: 0, duration: 30, props: { text: "👀 Outfit check", x: 50, y: 15, fontSize: 36, color: "var(--text-primary)", animation: "fadeIn" } },
      { type: "video", startFrame: 30, duration: 90, props: { x: 50, y: 50, width: 100, height: 100, transition: "slideLeft" }, placeholder: { label: "Look 1", accept: "video/*" } },
      { type: "video", startFrame: 120, duration: 90, props: { x: 50, y: 50, width: 100, height: 100, transition: "slideLeft" }, placeholder: { label: "Look 2", accept: "video/*" } },
      { type: "video", startFrame: 210, duration: 90, props: { x: 50, y: 50, width: 100, height: 100, transition: "slideLeft" }, placeholder: { label: "Look 3", accept: "video/*" } },
      { type: "text", startFrame: 300, duration: 60, props: { text: "Lequel préfères-tu ? 💬", x: 50, y: 80, fontSize: 28, color: "var(--text-primary)", animation: "bounce" } },
    ],
  },
  {
    id: "day-in-life",
    name: "Day in the life",
    description: "Vlog rapide de 15s, routine quotidienne version TikTok",
    duration: 15,
    aspectRatio: "9:16",
    icon: "🌅",
    compatibleDna: false,
    scenes: [
      { type: "text", startFrame: 0, duration: 30, props: { text: "🌅 Morning routine", x: 50, y: 20, fontSize: 32, color: "var(--text-primary)", animation: "fadeIn" } },
      { type: "video", startFrame: 30, duration: 60, props: { x: 50, y: 50, width: 100, height: 100 }, placeholder: { label: "Matin", accept: "video/*" } },
      { type: "video", startFrame: 90, duration: 60, props: { x: 50, y: 50, width: 100, height: 100 }, placeholder: { label: "Après-midi", accept: "video/*" } },
      { type: "video", startFrame: 150, duration: 60, props: { x: 50, y: 50, width: 100, height: 100 }, placeholder: { label: "Soir", accept: "video/*" } },
      { type: "video", startFrame: 210, duration: 60, props: { x: 50, y: 50, width: 100, height: 100 }, placeholder: { label: "Night", accept: "video/*" } },
      { type: "text", startFrame: 270, duration: 90, props: { text: "Same day, different vibe ✨", x: 50, y: 80, fontSize: 24, color: "var(--accent)", animation: "slideUp" } },
    ],
  },
  {
    id: "before-after",
    name: "Before / After",
    description: "Transition avant/après pour transformations",
    duration: 10,
    aspectRatio: "9:16",
    icon: "🔄",
    compatibleDna: true,
    scenes: [
      { type: "text", startFrame: 0, duration: 30, props: { text: "Before", x: 50, y: 15, fontSize: 42, color: "var(--danger)", animation: "fadeIn" } },
      { type: "image", startFrame: 30, duration: 90, props: { x: 50, y: 50, width: 100, height: 100, animation: "fadeIn" }, placeholder: { label: "Avant", accept: "image/*" } },
      { type: "text", startFrame: 120, duration: 30, props: { text: "→ After", x: 50, y: 15, fontSize: 42, color: "var(--success)", animation: "slideUp" } },
      { type: "image", startFrame: 150, duration: 150, props: { x: 50, y: 50, width: 100, height: 100, animation: "zoomIn" }, placeholder: { label: "Après", accept: "image/*" } },
    ],
  },
  {
    id: "quote-inspiring",
    name: "Quote inspirante",
    description: "Citation inspirante sur fond animé + musique douce",
    duration: 10,
    aspectRatio: "1:1",
    icon: "💬",
    compatibleDna: true,
    scenes: [
      { type: "text", startFrame: 0, duration: 150, props: { text: '"Le succès, c\'est de tomber sept fois, se relever huit."', x: 50, y: 40, fontSize: 32, color: "var(--text-primary)", fontFamily: "serif", animation: "fadeIn" } },
      { type: "text", startFrame: 150, duration: 60, props: { text: ",  Proverb", x: 50, y: 65, fontSize: 20, color: "rgba(255,255,255,0.5)", animation: "fadeIn" } },
      { type: "text", startFrame: 210, duration: 90, props: { text: "✨ halo-talent.com", x: 50, y: 85, fontSize: 16, color: "var(--accent)", animation: "slideUp" } },
    ],
  },
  {
    id: "product-showcase",
    name: "Product showcase",
    description: "Mise en valeur produit pour marques et créateurs",
    duration: 12,
    aspectRatio: "9:16",
    icon: "📦",
    compatibleDna: true,
    scenes: [
      { type: "text", startFrame: 0, duration: 30, props: { text: "✨ Nouvelle collection", x: 50, y: 15, fontSize: 30, color: "var(--text-primary)", animation: "fadeIn" } },
      { type: "video", startFrame: 30, duration: 90, props: { x: 50, y: 50, width: 100, height: 60, transition: "fade" }, placeholder: { label: "Vidéo produit", accept: "video/*" } },
      { type: "text", startFrame: 120, duration: 60, props: { text: "🔥 Qualité premium", x: 50, y: 75, fontSize: 24, color: "var(--accent)", animation: "slideUp" } },
      { type: "text", startFrame: 180, duration: 60, props: { text: "Livraison offerte 🔗", x: 50, y: 85, fontSize: 20, color: "var(--text-primary)", animation: "fadeIn" } },
      { type: "text", startFrame: 240, duration: 120, props: { text: "Lien en bio ⬇️", x: 50, y: 90, fontSize: 18, color: "var(--success)", animation: "bounce" } },
    ],
  },
  {
    id: "transition-reel",
    name: "Transition reel",
    description: "Reel tendance avec transitions rapides et textes dynamiques",
    duration: 10,
    aspectRatio: "9:16",
    icon: "⚡",
    compatibleDna: false,
    scenes: [
      { type: "video", startFrame: 0, duration: 50, props: { x: 50, y: 50, width: 100, height: 100, transition: "slideRight" }, placeholder: { label: "Clip 1", accept: "video/*" } },
      { type: "text", startFrame: 10, duration: 30, props: { text: "PART 1", x: 50, y: 50, fontSize: 48, color: "var(--text-primary)", animation: "fadeIn" } },
      { type: "video", startFrame: 50, duration: 50, props: { x: 50, y: 50, width: 100, height: 100, transition: "slideLeft" }, placeholder: { label: "Clip 2", accept: "video/*" } },
      { type: "text", startFrame: 60, duration: 30, props: { text: "PART 2", x: 50, y: 50, fontSize: 48, color: "var(--text-primary)", animation: "fadeIn" } },
      { type: "video", startFrame: 100, duration: 50, props: { x: 50, y: 50, width: 100, height: 100, transition: "slideLeft" }, placeholder: { label: "Clip 3", accept: "video/*" } },
      { type: "text", startFrame: 110, duration: 30, props: { text: "PART 3", x: 50, y: 50, fontSize: 48, color: "var(--text-primary)", animation: "fadeIn" } },
      { type: "video", startFrame: 150, duration: 50, props: { x: 50, y: 50, width: 100, height: 100, transition: "fade" }, placeholder: { label: "Clip 4", accept: "video/*" } },
      { type: "text", startFrame: 160, duration: 30, props: { text: "Lequel est ton pref ? ⬇️", x: 50, y: 80, fontSize: 20, color: "var(--accent)", animation: "bounce" } },
    ],
  },
];

export const STICKERS: StickerDef[] = [
  // Emojis
  { id: "s-fire", emoji: "🔥", label: "Fire", category: "emoji" },
  { id: "s-heart", emoji: "❤️", label: "Coeur", category: "emoji" },
  { id: "s-star", emoji: "⭐", label: "Star", category: "emoji" },
  { id: "s-clap", emoji: "👏", label: "Clap", category: "emoji" },
  { id: "s-ok", emoji: "👍", label: "OK", category: "emoji" },
  { id: "s-rocket", emoji: "🚀", label: "Rocket", category: "emoji" },
  { id: "s-crown", emoji: "👑", label: "Crown", category: "emoji" },
  { id: "s-sparkle", emoji: "✨", label: "Sparkle", category: "emoji" },
  { id: "s-light", emoji: "💡", label: "Idea", category: "emoji" },
  { id: "s-target", emoji: "🎯", label: "Target", category: "emoji" },
  { id: "s-money", emoji: "💰", label: "Money", category: "emoji" },
  { id: "s-party", emoji: "🎉", label: "Party", category: "emoji" },
  { id: "s-muscle", emoji: "💪", label: "Muscle", category: "emoji" },
  { id: "s-eyes", emoji: "👀", label: "Eyes", category: "emoji" },
  { id: "s-100", emoji: "💯", label: "100", category: "emoji" },
  // Shapes
  { id: "s-circle", emoji: "⭕", label: "Cercle", category: "shape" },
  { id: "s-square", emoji: "🟦", label: "Carré", category: "shape" },
  { id: "s-diamond", emoji: "🔷", label: "Diamant", category: "shape" },
  { id: "s-triangle", emoji: "🔺", label: "Triangle", category: "shape" },
  { id: "s-heart-shape", emoji: "💜", label: "Heart", category: "shape" },
  // Arrows
  { id: "s-up", emoji: "⬆️", label: "Haut", category: "arrow" },
  { id: "s-down", emoji: "⬇️", label: "Bas", category: "arrow" },
  { id: "s-right", emoji: "➡️", label: "Droite", category: "arrow" },
  { id: "s-left", emoji: "⬅️", label: "Gauche", category: "arrow" },
  { id: "s-swirl", emoji: "🔃", label: "Rotation", category: "arrow" },
  // Badges
  { id: "s-new", emoji: "🆕", label: "New", category: "badge" },
  { id: "s-hot", emoji: "🆒", label: "Cool", category: "badge" },
  { id: "s-top", emoji: "🔝", label: "Top", category: "badge" },
  { id: "s-free", emoji: "🆓", label: "Free", category: "badge" },
  { id: "s-soon", emoji: "🔜", label: "Soon", category: "badge" },
  // Frames/Borders
  { id: "s-frame-dots", emoji: "🔲", label: "Bordure points", category: "frame" },
  { id: "s-frame-star", emoji: "🌟", label: "Cadre étoile", category: "frame" },
  { id: "s-rainbow", emoji: "🌈", label: "Arc-en-ciel", category: "frame" },
];

export const STICKER_CATEGORIES = [
  { id: "emoji", label: "Émojis", icon: "😊" },
  { id: "shape", label: "Formes", icon: "🔷" },
  { id: "arrow", label: "Flèches", icon: "➡️" },
  { id: "badge", label: "Badges", icon: "🏷️" },
  { id: "frame", label: "Cadres", icon: "🖼️" },
];
