import type { Application, AuditLog, InternalNote } from "./types";

export const applications: Application[] = [
  {
    id: "1",
    created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    full_name: "Sarah K.",
    email: "sarah.k@example.com",
    phone: "+33 6 12 34 56 78",
    department: "Digital Creators",
    platforms: ["TikTok", "Instagram"],
    current_monthly_revenue: "3 000 - 5 000 €",
    ai_score: 87,
    ai_analysis: {
      score_total: 87,
      scores: { coherence: 18, potential: 20, communication: 17, alignment: 19, feasibility: 13 },
      strengths: [
        "Très forte cohérence entre son audience et notre département Digital Creators",
        "Excellent niveau de communication écrite, pitch clair et structuré",
        "Alignement parfait avec les valeurs de transparence et souveraineté",
      ],
      weaknesses: [
        "Revenus encore modestes, potentiel de scale à confirmer",
        "Présence uniquement sur deux plateformes, dépendance au TikTok",
      ],
      recommendation: "approve",
      reasoning:
        "Profil solide avec un fort alignement culturel. Son potentiel de croissance est significatif et sa communication est remarquable.",
    },
    status: "pending",
    avatar_url: null,
    country: "FR",
    age: 24,
    social_links: { TikTok: "https://tiktok.com/@sarah.k", Instagram: "https://instagram.com/sarah.k" },
    goals: "Je souhaite développer mon activité de création de contenu lifestyle et beauté à plein temps, tout en gardant le contrôle créatif total sur mon image et mes partenariats.",
    why_us:
      "J'ai été recommandée par une amie créatrice qui est chez vous depuis 6 mois. Ce qui m'a tout de suite parlé, c'est votre approche de la commission dégressive et la transparence radicale sur les contrats. Dans l'industrie où j'ai vu des amies se faire avoir par des clauses abusives, votre éthique fait la différence.",
    concerns:
      "J'hésite encore car je viens juste d'atteindre 10k abonnés sur TikTok et j'ai peur de ne pas être assez 'établie' pour une maison comme la vôtre.",
    manager_id: null,
    manager_name: null,
  },
  {
    id: "2",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    full_name: "Lucas M.",
    email: "lucas.m@example.com",
    phone: "+33 6 98 76 54 32",
    department: "Music & Performing Arts",
    platforms: ["YouTube", "Instagram", "TikTok"],
    current_monthly_revenue: "8 000 - 12 000 €",
    ai_score: 74,
    ai_analysis: {
      score_total: 74,
      scores: { coherence: 16, potential: 17, communication: 14, alignment: 15, feasibility: 12 },
      strengths: [
        "Présence multi-plateforme solide avec audience engagée",
        "Revenus déjà significatifs montrant une capacité à monétiser",
      ],
      weaknesses: [
        "Communication écrite perfectible, réponses courtes et peu détaillées",
        "Parcours un peu flou sur les 12 derniers mois",
      ],
      recommendation: "review",
      reasoning:
        "Bon profil avec un potentiel commercial évident, mais nécessite un entretien approfondi pour clarifier ses attentes et sa vision.",
    },
    status: "pending",
    avatar_url: null,
    country: "FR",
    age: 28,
    social_links: {
      YouTube: "https://youtube.com/@lucas.m",
      Instagram: "https://instagram.com/lucas.m",
      TikTok: "https://tiktok.com/@lucas.m",
    },
    goals: "Multiplier mes sources de revenus en tant que musicien indépendant et structurer mon activité pour en vivre à 100%.",
    why_us: "Je connais plusieurs créateurs chez vous et ils parlent tous de la qualité de l'accompagnement. J'aimerais en savoir plus.",
    concerns: "Je suis actuellement en tournée, je ne pourrai pas passer à votre bureau avant plusieurs semaines.",
    manager_id: null,
    manager_name: null,
  },
  {
    id: "3",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    full_name: "Emma V.",
    email: "emma.v@example.com",
    phone: null,
    department: "Music & Performing Arts",
    platforms: ["YouTube"],
    current_monthly_revenue: "15 000 - 25 000 €",
    ai_score: 93,
    ai_analysis: {
      score_total: 93,
      scores: { coherence: 20, potential: 19, communication: 19, alignment: 18, feasibility: 17 },
      strengths: [
        "Profil exceptionnel avec des revenus déjà très solides",
        "Vision stratégique claire et ambitieuse",
        "Excellente qualité de communication, réponse très détaillée sur le 'pourquoi nous'",
      ],
      weaknesses: ["Dépendance quasi exclusive à YouTube comme source de revenus"],
      recommendation: "approve",
      reasoning:
        "Candidature prioritaire. Profil mature avec une vision claire et des revenus établis. Recommandation d'approbation immédiate.",
    },
    status: "review",
    avatar_url: null,
    country: "BE",
    age: 31,
    social_links: { YouTube: "https://youtube.com/@emma.v" },
    goals: "Professionnaliser ma structure et déléguer la gestion administrative pour me concentrer sur la création musicale et les partenariats stratégiques.",
    why_us:
      "Après 5 ans en indépendant, j'ai atteint un plafond dans ma gestion solo. J'ai besoin d'une équipe qui comprend vraiment le marché des créateurs et qui peut négocier des deals que je n'aurais jamais eu accès seule. Votre approche de la souveraineté créative m'a convaincue.",
    concerns: null,
    manager_id: null,
    manager_name: null,
  },
  {
    id: "4",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    full_name: "Alexandre D.",
    email: "alex.d@example.com",
    phone: "+32 4 87 65 43 21",
    department: "Sport & Lifestyle",
    platforms: ["Instagram", "TikTok"],
    current_monthly_revenue: "2 000 - 4 000 €",
    ai_score: 45,
    ai_analysis: {
      score_total: 45,
      scores: { coherence: 10, potential: 12, communication: 8, alignment: 9, feasibility: 6 },
      strengths: ["Belle présence visuelle sur Instagram", "Thématique fitness en pleine croissance"],
      weaknesses: [
        "Communication très faible, réponses quasi inexistantes au questionnaire",
        "Manque de clarté sur ses objectifs et sa vision",
        "Revenus très modestes sans stratégie de croissance claire",
      ],
      recommendation: "reject",
      reasoning:
        "Profil trop peu mature pour un accompagnement à ce stade. Le manque d'investissement dans le questionnaire et l'absence de vision stratégique sont des signaux d'alarme.",
    },
    status: "pending",
    avatar_url: null,
    country: "BE",
    age: 22,
    social_links: { Instagram: "https://instagram.com/alex.d", TikTok: "https://tiktok.com/@alex.d" },
    goals: "Devenir influenceur fitness à plein temps.",
    why_us: "J'ai vu votre site, ça a l'air bien.",
    concerns: null,
    manager_id: null,
    manager_name: null,
  },
  {
    id: "5",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    full_name: "Inès D.",
    email: "ines.d@example.com",
    phone: "+33 6 45 67 89 01",
    department: "Digital Creators",
    platforms: ["OnlyFans", "Instagram", "Twitter"],
    current_monthly_revenue: "20 000 - 35 000 €",
    ai_score: 91,
    ai_analysis: {
      score_total: 91,
      scores: { coherence: 19, potential: 18, communication: 18, alignment: 20, feasibility: 16 },
      strengths: [
        "Revenus très élevés démontrant une maîtrise complète de la monétisation",
        "Alignement parfait avec les valeurs de souveraineté et transparence",
        "Discours très mature sur la gestion de carrière",
      ],
      weaknesses: [
        "Dépendance forte à OnlyFans (75% des revenus)",
        "Souhaite une discrétion totale, ce qui limite les opportunités cross-canal",
      ],
      recommendation: "approve",
      reasoning:
        "Candidature excellente d'une créatrice établie avec une vision claire. Son alignement avec nos valeurs est remarquable.",
    },
    status: "approved",
    avatar_url: null,
    country: "FR",
    age: 27,
    social_links: {
      OnlyFans: "https://onlyfans.com/ines.d",
      Instagram: "https://instagram.com/ines.d",
      Twitter: "https://twitter.com/ines.d",
    },
    goals: "Sécuriser mon business et le faire évoluer vers des sources de revenus plus diversifiées, notamment le brand deals et les produits digitaux.",
    why_us:
      "Je suis suivie par une agence généraliste depuis 2 ans et je suis frustrée par le manque de transparence sur les commissions et les contrats. Un contact dans le milieu m'a parlé de votre modèle de commission dégressive et de votre approche éthique. C'est exactement ce que je cherche : un partenariat, pas une extraction.",
    concerns: "J'ai besoin de garanties sur la discrétion et la protection de mon identité en ligne.",
    manager_id: "m1",
    manager_name: "Marc A.",
  },
  {
    id: "6",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    full_name: "Hugo P.",
    email: "hugo.p@example.com",
    phone: null,
    department: "Business & Thought Leadership",
    platforms: ["YouTube", "LinkedIn"],
    current_monthly_revenue: "5 000 - 8 000 €",
    ai_score: 68,
    ai_analysis: {
      score_total: 68,
      scores: { coherence: 15, potential: 14, communication: 13, alignment: 14, feasibility: 12 },
      strengths: ["Positionnement unique sur le contenu business/leadership", "Bon niveau d'expertise"],
      weaknesses: [
        "Audience encore modeste sur YouTube",
        "Présence LinkedIn à développer",
        "Pas encore de monétisation claire au-delà des sponsors",
      ],
      recommendation: "review",
      reasoning:
        "Niche intéressante et positionnement prometteur, mais le modèle économique est encore à structurer. Entretien recommandé.",
    },
    status: "rejected",
    avatar_url: null,
    country: "FR",
    age: 34,
    social_links: { YouTube: "https://youtube.com/@hugo.p", LinkedIn: "https://linkedin.com/in/hugo.p" },
    goals: "Monétiser mon expertise en conseil et contenu business à haut niveau.",
    why_us: "Je cherche une structure qui comprend le marché du thought leadership en France, pas juste du divertissement.",
    concerns: "Je ne suis pas sûr de pouvoir consacrer assez de temps au développement de mon audience.",
    manager_id: null,
    manager_name: null,
  },
];

export const auditLogs: Record<string, AuditLog[]> = {
  "3": [
    {
      id: "l1",
      application_id: "3",
      action: "Candidature soumise",
      actor: "Emma V.",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    },
    {
      id: "l2",
      application_id: "3",
      action: "Mise en review",
      actor: "Marc A.",
      created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
      metadata: { note: "Profil prometteur, demande entretien téléphonique" },
    },
  ],
  "5": [
    {
      id: "l3",
      application_id: "5",
      action: "Candidature soumise",
      actor: "Inès D.",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    },
    {
      id: "l4",
      application_id: "5",
      action: "Analyse IA générée",
      actor: "Claude",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 72 + 1000).toISOString(),
    },
    {
      id: "l5",
      application_id: "5",
      action: "Approuvée avec contrat",
      actor: "Marc A.",
      created_at: new Date(Date.now() - 1000 * 60 * 36).toISOString(),
    },
  ],
};

export const internalNotes: Record<string, InternalNote[]> = {
  "1": [
    {
      id: "n1",
      application_id: "1",
      author: "Sophie L.",
      content: "A rappeler cette semaine, elle semble motivée mais hésitante.",
      created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    },
  ],
  "3": [
    {
      id: "n2",
      application_id: "3",
      author: "Marc A.",
      content: "Vérifier sa situation contractuelle actuelle, elle travaille peut-être avec une autre structure.",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    },
  ],
};

export const departments = [
  "Music & Performing Arts",
  "Sport & Lifestyle",
  "Business & Thought Leadership",
  "Digital Creators",
  "Talent Premium",
];

export const platformOptions = [
  "YouTube",
  "Instagram",
  "TikTok",
  "OnlyFans",
  "Twitter",
  "LinkedIn",
  "Snapchat",
  "Twitch",
];
